### ISSUE TITLE
Specify supported versions of npm and node

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/nr-fom#103]
This includes local, docker-compose and openshift.

**Comment by gormless87** [comment]
PS C:\Users\basil.vandegriend> node --version
v14.17.0
PS C:\Users\basil.vandegriend> npm -version
6.14.13

o-yi.liu@CA-L58347M3 MINGW64 /d/Workspace/FOM/nr-fom (main)
$ node --version
v14.16.0



po-yi.liu@CA-L58347M3 MINGW64 /d/Workspace/FOM/nr-fom (main)
$ npm --version
6.14.11
