### ISSUE TITLE
Test & Document FOM Test scripts/steps after FOM TEST route cutover

### ISSUE THREAD

**Issue by ArogeG** [bcgov/nr-fom#110]
Test FOM Test after cutover
Please document test scrips for FOM during testing after the FOM route cutover and share with team for testing 

AC
- Test FOM after route changes to new TEST route
-Document and share test steps/scripts with team 
-PO is able to run test using documentation.

**Comment by ArogeG** [comment]
I think this has been completed by @amee99073, we should probably close this if there are no issues.

**Comment by amee99073** [comment]
Not done making test scripts yet - so still open.

**Comment by ArogeG** [comment]
@amee99073 I might have missed this, but can you please point me to the location of the test scripts. Thanks.
