### ISSUE TITLE
Dark deployments (night)

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/nr-fom#117]
Deployment integration happens any time, but deployments happen during off hours, like 4 AM.

Initially intended for demo environment.

**Comment by basilv** [comment]
The typical deployment of a change should be zero outage, as Openshift spins up new nodes with the new version, then after they are healthy brings down the old ones. Unless with the single node database, if it is updated that would cause a brief outage (as I assume it is configured to not have more than 1 node). So probably higher priority to make sure the database isn't touched unless it has an actual change, after which point this particular improvement is likely not necessary.

**Comment by DerekRoberts** [comment]
https://github.com/bcgov/greenfield-template/issues/485

**Comment by DerekRoberts** [comment]
Zero downtime deployments are now in please, leaving the database alone.  Replacing the database, which can be done with `overwrite: true` or by deleting it, still causes an outage.

See https://github.com/bcgov/nr-fom/pull/306
