### ISSUE TITLE
SonarCloud Issues and Low Code Coverage Resulting From Admin Separation

### ISSUE THREAD

**Issue by ianliuwk1019** [bcgov/nr-fom#121]
**Pipeline Gate Failed for PR for Admin Separation**
[SonarCloud Report](https://sonarcloud.io/summary/new_code?id=nr-fom&pullRequest=112) shows some code smells and low coverage. Do we want to address them?

There is another ticket to address adding minimum (1 for each) frontend components tests but to achieve 80% might be very difficult.

**Comment by DerekRoberts** [comment]
@ianliuwk1019 Thankfully 80% is only required for new components!  Thanks for logging this.

**Comment by basilv** [comment]
Most of the code smells are not worth fixing or are false positives and can be resolved(ignored). This is essentially what I did for the public component. (Code coverage is a completely separate topic though)

**Comment by gormless87** [comment]
Closing as #158 addressed major updates and Renovatebot is now in place.
