### ISSUE TITLE
Install SSL Certs - for FOM Cutover

### ISSUE THREAD

**Issue by franTarkenton** [bcgov/nr-fom#122]
* uninstall the older version of certbot in the repo and install the newest version from the common service team (https://github.com/BCDevOps/certbot)
* Issue service desk request for prod cert renewals
* Monitor and close once the prod certs are renewed and installed for all routes starting with fom.nrs.gov.bc.ca

**Comment by franTarkenton** [comment]
Issued the following request with the service desk to renew prod certs:
* https://apps.nrs.gov.bc.ca/int/jira/servicedesk/customer/portal/1/SD-27962

**Comment by gormless87** [comment]
@franTarkenton to document necessary steps here

**Comment by franTarkenton** [comment]
# Background

* currently fom.nrs.gov.bc.ca is configured by the IIT DNS.  That domain is simply re-directed to the openshift cluster, ie (142.34.194.118).
* When a route on the openshift cluster is defined using the domain (fom.nrs.gov.bc.ca) the traffic gets captured, by that route, which then sends to the service and then to the pod.

# Cutover Issues

* during the cutover there is the potential for the old NRDK based deployment to refer to the same route as the new greenfield pipeline based deployment.

# Mitigation Action

* During the cutover, we want to delete the following old routes before we use the new greenfield based prod deployment.
    * https://fom.nrs.gov.bc.ca/public
    * https://fom.nrs.gov.bc.ca/admin
    * https://fom.nrs.gov.bc.ca/api
  
* After the greenfield pipeline deployment has run, we need to manually trigger a certbot job/run, which will install the certs onto the routes that have just been created by the greenfield pipeline.

`oc create job "certbot-manual-$(date +%s)" --from=cronjob/certbot`

* double check that the urls above all function perfectly

* remove the manual job after it has completed running

`oc get job -o name | grep -F -e '-manual-' | xargs oc delete`

# Additional Information

* [Confluence page describing how to set up vanity url  and certs](https://apps.nrs.gov.bc.ca/int/confluence/pages/viewpage.action?pageId=95654219)
* [bcdevops certbot documentation](https://github.com/BCDevOps/certbot/blob/master/docker/README.md)

**Comment by franTarkenton** [comment]
I have updated the certbot version installed in the prod namespace for fom, and triggered a manual build.  The manual build reports:
`All authorizations were not finalized by the CA.`

Concerned there may have been a mistake made in the istore request for the certs

Link to the service desk ticket:
https://apps.nrs.gov.bc.ca/int/jira/projects/SD/queues/issue/SD-42213

**Comment by ArogeG** [comment]
Come Aug 9, if we don't have Entrust, run cert box to use Lets Encrypt cert.
