### ISSUE TITLE
Resolve 54 dependabot alerts

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/nr-fom#123]
And counting.
https://github.com/bcgov/nr-fom/security/dependabot

**Comment by basilv** [comment]
Dependabot link above doesn't work for me. Is access to it limited to GitHub admins perhaps?

**Comment by DerekRoberts** [comment]
@basilv Let's find out!  You're now an admin.

**Comment by basilv** [comment]
Confirmed, I can now access the Dependabot alerts. I believe that GitHub actually treats security review access as a special permission only assigned to admins by default, so its possible to create a separate group other than admins to provide this access, or just grant access to all regular contributors, if you want to avoid me/others having admin.

**Comment by DerekRoberts** [comment]
@basil Good idea!  Admin rights removed, but now everyone in FSA should be able to see security alerts.  Please confirm again?

Issue: https://github.com/bcgov/nr-fom/issues/144

**Comment by basilv** [comment]
I still have access, so all good!

**Comment by gormless87** [comment]
See #158
