### ISSUE TITLE
OC_TOKENs all suddenly expiring

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/nr-fom#129]
Not sure what caused these tokens to suddenly expire at once, but they're replaceable though the OpenShift console.

**Comment by ArogeG** [comment]
We should probably create a spike ticket to investigate why they all expired. @DerekRoberts did you get a notification about the expired tokens?

**Comment by DerekRoberts** [comment]
@ArogeG No, the pipeline started failing without warning. I'm guessing platform services ran an update, but don't have an answer.

**Comment by ArogeG** [comment]
Ok, thanks.
