### ISSUE TITLE
OC pipeline tokens suddenly expiring

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/nr-fom#152]
The week of July 11-15 several of our long-lived OpenShift tokens for the GitHub Actions expired.  It appears to be happening again this week, July 18-22, so there's cause to investigate.

**Comment by ArogeG** [comment]
@DerekRoberts are tokens still expiring or has this been fixed?

**Comment by DerekRoberts** [comment]
@ArogeG It hasn't happened since.  I suspect the platform team occasionally updates their all-namespace tokens, causing this issue.  It should be occasional at best.

**Comment by DerekRoberts** [comment]
This doesn't appear to be recurring.  Closing.
