### ISSUE TITLE
Update FOM Splash Screen

### ISSUE THREAD

**Issue by ArogeG** [bcgov/nr-fom#177]
Update splash screen in FOM. To go to the NRS helpdesk email: nrmenquiries@gov.bc.ca

![image.png](https://images.zenhubusercontent.com/62a1029ce9497c39c087ab8b/fb6a3b24-05d5-4c7d-9b16-7069c6610904)

**Comment by webgismd** [comment]
@ArogeG I think there might not be anything to do here. Unless there has been a change from last week?

**Comment by ArogeG** [comment]
I agree, I was hoping to confirm the email address with you before closing the ticket. Thanks.
