### ISSUE TITLE
Use var for FOM email notifications, not hard coded

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/nr-fom#196]
Throw this into an environment variable and populate using the GitHub workflows.  We can still use a shared email as a fallback/default.

https://github.com/bcgov/nr-fom/blob/main/api/src/core/mail/mail.service.ts#L19

**Comment by basilv** [comment]
See also #198, probably worth doing the two together.

**Comment by DerekRoberts** [comment]
Fixed by https://github.com/bcgov/nr-fom/pull/225
