### ISSUE TITLE
Online public notice - show 'disclaimer' after each notice

### ISSUE THREAD

**Issue by basilv** [bcgov/nr-fom#206]
For the public site list of public notices, show the 'disclaimer' text after each notice and reword to "This FOM...".

Disclaimer text currently is: "These FOM can be relied upon by the FOM holder for the purpose of a cutting permit or road permit application, or the issuance of a Timber Sales License until the date three years after commencement of the public review and commenting period."

**Comment by DerekRoberts** [comment]
@basilv Sounds good, but deploying to a PR is generally good enough.

**Comment by basilv** [comment]
Hmm, @DerekRoberts you might be right, will have to work out the logistics with Julius, but for now I've removed the statement regarding the demo env.
