### ISSUE TITLE
Revise FOM email notifications

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/nr-fom#209]
Use the pipeline to handle where FOM update notifications are emailed.

PROD - already handled via DB
TEST - FLNR.AdminServicesCariboo@gov.bc.ca
DEMO - FLNR.AdminServicesCariboo@gov.bc.ca
DEV - SIBIFSAF@victoria1.gov.bc.ca

**Comment by ArogeG** [comment]
@DerekRoberts if these notifications are technical, irrespective of the environment they should all be sent to SIBIFSAF@victoria1.gov.bc.ca. 

Only business notifications should go to the business email. 

Let me know what sort of email notification is being referred to here please.

**Comment by DerekRoberts** [comment]
@ArogeG Please speak with @basilv.  I'll happily implement whatever is decided on.
