### ISSUE TITLE
Support posting public notice prior to commenting open date.

### ISSUE THREAD

**Issue by basilv** [bcgov/nr-fom#210]
As a licensee creating a FOM, I want the option to have the online public notice posted (visible to public) before the FOM reaches the commenting open period, so that the public can prepare for when commenting does open.

From a UI perspective, this can be achieved by having a "Post Notice" button on the create/edit online public notice screen. If this button is not clicked, then behavior remains the same as now - the public notice is made visible when the FOM reaches commenting open status. If the button is clicked, this immediately makes the online public notice available (possibly subject to cache refresh).

If a public notice is posted prior to commenting open, then we should not show the "View Details" button and instead have text explaining when commenting will open. Alternatively the business suggested keeping the "View Details" button and then have a popup if it is clicked. We can debate options and wording.

Points to clarify:
1. Once a notice is posted, prevent any further edits to it? (The FOM itself would still be editable while in initial state - but maybe only certain fields, as things like the commenting period are shown in the public notice).
2. There is flexibility in wording / UI design. The term "Post Notice" is strongly preferred over "Publish notice" as we want to avoid confusion with the FOM workflow, but alternative terms could be considered.

Technical Design 
1. Need a state for public notice separate from the FOM project state (a boolean posted flag?) as a new column. Maybe want multiple states: initial, posted before commenting open, posted with commenting open, closed, and update separately/linked to FOM project states?
2. Need to review how public notices are cached. Caching frequency may need to change (e.g. reload each hour), or we limit update of public site to next day - question for business.
3. Need to change how public notices are loaded for public. Should our new state be used just for posting prior to comment open? That's one option, the other option is on comment open we update the posted state on public notice.

Tasks:
1. Add column
2. Change API backend for column
3. Change Admin to have post notice button 
4. Admin prevent editing once posted
5. API - change logic for loading/caching public notices for public site
6. Public - display view details button differently when posted before commenting open.

**Comment by basilv** [comment]
Solution option 2 is keep the single publish button with a separate publish date for the public notice. The FOM project itself (as well as the public notice) will both be non-editable after publish.

**Comment by basilv** [comment]
TODAY: FOM: Initial -> Published -> Commenting Open

Option 1 - separate 'post notice' option on public notice screen (still optional)
Option 1: have a separate state on public notice entity: INITIAL -> PUBLISH -> VISIBLE -> NOT VISIBLE (triggered commenting closed)
business rule: can't edit commenting period on project when state = initial but public notice state = published


Option 2 - only one publish button
Option 2: FUTURE: Initial -> Published -> [PublicNoticePosted ->] Commenting Open

FUTURE OPTION x - don't change states, pull public notice based on dates not states


Option 1 workflow
0. create & edit the FOM & public notice
1. optionally enter post notice date (if not entered defaults to commenting open date)
2. optionally click 'post notice' button
3. optionally edit the FOM - could be confusing 
4. click publish later.
Issue: what if I forget to click publish, what if I forget to click post notice (should just display automatically on commenting open date)


Option 2 workflow
0. create & edit the FOM & public notice
1. optionally enter post notice date (if not entered defaults to commenting open date)
2. click publish

**Comment by ianliuwk1019** [comment]
While there might still be some discussion with Julius, temporarily working toward:
```
Option 2 workflow
0. create & edit the FOM & public notice

optionally enter post notice date (if not entered defaults to commenting open date)
click publish
``` from previous comment.

**Comment by ianliuwk1019** [comment]
Two wordings suggested by Julius are implemented:
- Admin: new post_date labled as '**Notice Publishing Date**'.
- Public - Public Notices page when detail button is hidden (FOM not available yet): **This FOM will be available for public review and comment starting “insert commenting open date”**

- A warning popup at admin (add/edit online public notice page) when commenting_open_date has not been set yet (INITIAL status) to ask user to set commenting_open_date first.

@basilv

**Comment by ianliuwk1019** [comment]
PR#393 merged to main, deployed to TEST environment.
Pending for business review (or further user testing).

**Comment by ianliuwk1019** [comment]
Add Julius's feedback from week of July 10.
[https://app.zenhub.com/files/493404403/3d2b90fd-17b5-4264-98e2-2bda13b11ecc/download](https://app.zenhub.com/files/493404403/3d2b90fd-17b5-4264-98e2-2bda13b11ecc/download)

**Comment by ianliuwk1019** [comment]
Add Julius's feedback on more improvement from July 18.
[https://app.zenhub.com/files/493404403/073cc4b4-9b3f-4ce1-9204-7cb547e9aacb/download](https://app.zenhub.com/files/493404403/073cc4b4-9b3f-4ce1-9204-7cb547e9aacb/download)
