### ISSUE TITLE
Online public notice - include year-based timeline of operations -Backend changes

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-fom#222]
As legal staff working on FOM regulations
I want a statement on the online public notice for each FOM regarding the planned duration of operations using the following wording: "Road construction and harvesting of cutblocks depicted on this Forest Operations Map is scheduled to be conducted between YYYY and YYYY." where YYYY is the start and end years entered by the licensee in the Create/Edit Online Public Notice screen.
so that legal requirements are met.

**Tasks **

Add database columns for start & end year to the public_notice entity
Modify API back-end to accept these fields
Validation logic to treat these as mandatory fields. End year must be >= start year.

**Business requires this by 1st week in September

**Comment by ianliuwk1019** [comment]
The two columns are named:
'operation_start_year'
'operation_end_year'
