### ISSUE TITLE
Observability requirements for FOM

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-fom#224]

**Comment by basilv** [comment]
Documenting on FOM's confluence for now, partly because FOM GitHub doesn't have a wiki enabled
https://apps.nrs.gov.bc.ca/int/confluence/display/FOM/Observability+Requirements

Please advise if this should go elsewhere.

**Comment by DerekRoberts** [comment]
> Documenting on FOM's confluence for now, partly because FOM GitHub doesn't have a wiki enabled https://apps.nrs.gov.bc.ca/int/confluence/display/FOM/Observability+Requirements
> 
> Please advise if this should go elsewhere.

@basilv Wikis now enabled!

**Comment by basilv** [comment]
Awesome, thanks Derek - requirements moved to https://github.com/bcgov/nr-fom/wiki/Observability-Requirements

**Comment by ArogeG** [comment]
@basilv sounds good to keep the scope to performance and availability. I think priority should be given to public forms performance related to latency, CPU utilization, memory utilization, peak traffic, and error rate. We have a distribution email that we can use for alerts, I will add you and Ian to the distribution group. 

I wonder if it is important to get metrics on Mean time between failure to understand the average time between repairs. This might help with tracking patterns. 

At this point, I think it might be time to start exploring Opensearch. We can look into this next sprint. Thanks for documenting the requirements.
