### ISSUE TITLE
Deploy only FOM components that have changed

### ISSUE THREAD

**Issue by basilv** [bcgov/nr-fom#234]
As a prod deployer of FOM changes, I want only changed components to be deployed. This is especially true for the database, since as a single node any deployments to it will cause an outage. So if nothing else, just prevent database deployments if no changes to the database container / image.
(I thought we already had an issue for this but couldn't find it in GitHub, maybe it was in the greenfield template).

See before for the production deployment of FOM for what actually happened - only had a change to the public component, but deployed database and API. (I assume a rollout of admin and public happened, but too quickly to get all the details in the github log.
https://github.com/bcgov/nr-fom/runs/7958353284?check_suite_focus=true

**Comment by DerekRoberts** [comment]
https://github.com/bcgov/greenfield-template/issues/487

**Comment by DerekRoberts** [comment]
@basilv This is arguably implemented in https://github.com/bcgov/nr-fom/pull/306.  Databases and init (secrets) are not replaced at deployment, which is controlled in an Action with `overwrite: false`.
