### ISSUE TITLE
Strange pipeline behavior 'dev' public frontend does not show public-notices test data for 'Years of Operation' fields 

### ISSUE THREAD

**Issue by ianliuwk1019** [bcgov/nr-fom#252]
Details of this bug is mentioned in [#203](https://app.zenhub.com/workspaces/fsa-fingerprint-61f04f08304d3e001a4f2578/issues/bcgov/nr-fom/203).

> While Anne-Marie was testing on new PR for the minor label change that deploy from pipeline to 'dev' she found that the existing public-notices (4 current test data) on the public frontend does not have the new fields show up (for Years of Operations) while she checked the admin frontend with the same FOM record and the Years of Operations appear in admin.
> There was no code change for public frontend and only admin that time, nothing is wrong for public code and I checked with that as well after discussion with Anne-Marie.
> 
> However, while looking into frontend code, I also changed one more label at frontend although it was not mentioned from business, but just need to keep it consistent with the labeling change at admin. The pipeline redeployed with 'public' end change this time, and after deployment, the fields (for Years of Operation) shows up.
> 
> The strange behaviors of the public frontend described above need some investigation. It feels like the admin connects to the backend that has the database with test data migrated correctly while public connects to the backend that has the database with test data migration incorrectly, but how could that happen?
> This probably can be isolated only on 'dev' environment before PR merged into TEST as we were looking into 'test data', if TEST are being tested manually properly by Anne-Marie and Julius.
> 
>

**Comment by ianliuwk1019** [comment]
Details of this bug is mentioned in [#203](https://app.zenhub.com/workspaces/fsa-fingerprint-61f04f08304d3e001a4f2578/issues/bcgov/nr-fom/203).

> While Anne-Marie was testing on new PR for the minor label change that deploy from pipeline to 'dev' she found that the existing public-notices (4 current test data) on the public frontend does not have the new fields show up (for Years of Operations) while she checked the admin frontend with the same FOM record and the Years of Operations appear in admin.
> There was no code change for public frontend and only admin that time, nothing is wrong for public code and I checked with that as well after discussion with Anne-Marie.
> 
> However, while looking into frontend code, I also changed one more label at frontend although it was not mentioned from business, but just need to keep it consistent with the labeling change at admin. The pipeline redeployed with 'public' end change this time, and after deployment, the fields (for Years of Operation) shows up.
> 
> The strange behaviors of the public frontend described above need some investigation. It feels like the admin connects to the backend that has the database with test data migrated correctly while public connects to the backend that has the database with test data migration incorrectly, but how could that happen?
> This probably can be isolated only on 'dev' environment before PR merged into TEST as we were looking into 'test data', if TEST are being tested manually properly by Anne-Marie and Julius.
> 
>

**Comment by basilv** [comment]
I'm pretty sure this is due to caching - FOMs updated in Admin not yet shown in public due to the cache for the online public notice data, so not an actual issue. Problem resolves when redeploying API (forces cache refresh).
