### ISSUE TITLE
Strange deployment out of sync issue (TEST) on Openshift

### ISSUE THREAD

**Issue by ianliuwk1019** [bcgov/nr-fom#256]
The 'TEST' deployment is strange that we observed in few times that the deployment does not match current expectation (behavior in local vs TEST is different), or out of sync (missing functionalities) in components (could happen in either public/admin/api).

This detail is documented in the comment of this issue: https://app.zenhub.com/workspaces/fsa-fingerprint-61f04f08304d3e001a4f2578/issues/bcgov/nr-fom/253

> Anne-Marie reported on Friday (after deployment to TEST) the 'save' for the public notice on input form does not work for operations years fields, everything else did get saved.
> The pr that gets deployed to TEST has code change only in 'admin'. And the issue in TEST described above is unrelated to the code change (issue was in 'api').
> 
> Initial investigation was done on Friday after Anne-Marie reported, but could not find good reason why the deployment did not work for the new code change (on 'admin') and 'api' backend did not save operation years in database. I have checked the database columns for new fields are there in TEST (OpenShift), the fields shows up at frontend ('admin') in TEST, the http request sent correct years for both fields I selected in TEST to backend, the remaining component is why backend isn't saving the values selected while columns are there and are always empty after saving.... does not make any sense....
> 
> I conducted a subsequent PR that contains nothing change in each component (public/admin/api) and just a dummy space removal in code change in each component with Anne-Marie's help to approve and merge this dummy pr to 'main' branch. After deployment Anne-Marie did a test and pass her expectation. Everything now is good in TEST.
> 
> This is a strange behavior in Openshift deployment (or maybe from github action?). Something funny is going on. It might need Derek's assistance to look deeper in this issue. I feel, with only code change in only one component (in this case 'admin), some other components (in this case the issue component 'api) does not seem to keep the latest code/image for the deployment and out of sync.
> 
> Interesting note related to this issue (and happened in earlier vulnerability pr): Anne-Marie observed that the pr's TEST deployment did not even have operation years fields in 'admin' page, although nothing was changed to code but the package.json in 'api' component. However, due to later there was one more pr needed that day to correct the code at 'admin' TEST was being deployed again and we saw the operation year fields show up again in 'admin'.

**Comment by ianliuwk1019** [comment]
Just a screenshot for Derek if that help troubleshooting:
![image.png](https://images.zenhubusercontent.com/62a9ff93d8506f14758ef03a/65869571-99ce-4c10-872d-9b3c17aa354f)
pr#262 was just a dummy triggering build for only on 'api' to test if 'public' and 'admin' deployment were good.
@DerekRoberts

**Comment by DerekRoberts** [comment]
There's been some progress!  PRs pull from the PROD images, but FOM hasn't been going to PROD lately.   This should be changed to use TEST images in PRs, since that suits this environment.  I'll do this first in another repository, then bring the changes over here.
