### ISSUE TITLE
Configuration Driven Authorization for FOM

### ISSUE THREAD

**Issue by franTarkenton** [bcgov/nr-fom#272]
Building on work that the command line tool used for admin of fom users / roles: https://github.com/bcgov/nr_fsa2/issues/26

This ticket will read an Excel SS in onedrive and sync configurations defined in the SS with keycloak.  The job will run in openshfit as a cronjob.  This will enable Julius to make changes to the SS and have them reflected in Keycloak next time the cronjob runs.

**Comment by gormless87** [comment]
Closed in favor of skipping to a GUI for Julius
