### ISSUE TITLE
Create command line tool to add users and roles from FOM to keycloak

### ISSUE THREAD

**Issue by ConradBoydElliottGustafson** [bcgov/nr-fom#273]

**Comment by franTarkenton** [comment]
Created this repo for the code: https://github.com/bcgov/nr-fom-usermanager

**Comment by franTarkenton** [comment]
Code is working and has been tested.  Outstanding on this ticket:
* packaging to pypi for easy installation 95% complete
* update readme with instructions on installation
* copy github actions for the pypi build install upon merge to main.

**Comment by franTarkenton** [comment]
Almost at version 1.  Have auto build of pypi package.  Tested tool to add approx. 10 users to fom today.  Configured the service account in keycloak and documented what was done for that.
Fixed various bugs that were experienced when adding users using the fomuser cli tool.

Starting to think about keycloak config and how to define it in a manifest.  @ConradBoydElliottGustafson curious to get your ideas on how we might do this.

**Comment by franTarkenton** [comment]
Calling this done!
Instructions for install  / usage in readme.
packaged to pypi: https://pypi.org/project/FOMUserUtil/
