### ISSUE TITLE
Update FOM Demo with FOM TEST version

### ISSUE THREAD

**Issue by ArogeG** [bcgov/nr-fom#276]
**Describe the task**
Deploy recent features and enhancement to FOM DEMO to ensure that FOM TEST and FOM DEMO are in sync. 

**Acceptance Criteria**
- [ ] FOM DEMO is in sync with FOM TEST
- [ ] second
- [ ] third

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by DerekRoberts** [comment]
Pushed most recent code from main to demo.  This triggers a deployment.  Here's one way of doing that.

```bash
git checkout main
git pull
git checkout demo
git pull origin main --rebase
git push -f
```

Can someone please double-check the deployments?
https://fom-demo.apps.silver.devops.gov.bc.ca/admin
https://fom-demo.apps.silver.devops.gov.bc.ca/api
https://fom-demo.apps.silver.devops.gov.bc.ca/public

**Comment by basilv** [comment]
My 1st deploy merging main to demo didn't result in Openshift updating. Derek's 2nd deploy seemed to have caused openshift to update, Admin, API, and Public are up-to-date now.
