### ISSUE TITLE
FOM are saved in relation to Forest Stewardship Plan. Validation for FSP ID is required

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/nr-fom#278]
> We will need to retrieve the FSP_ID for FOM
> A forest stewardship plan (FSP) can have one or more FOM (Forest Operations Map)
> Currently, FOM are created, FSP ID's are related to those FOM but there is no Referential Integrity to the FOREST_STEWARDSHIP_PLAN.FSP_ID. Validation will eventually be required to ensure that the FSP_ID entered actually exists.
> Additionally, Forest stewardship Plans are related to Client Numbers in the FSP_AGREEMENT_HOLDER table FSP_ID to CLIENT_NUMBER.
> Once both CLIENT data and FSP data are available, the data in FOM will be validated and reliable.

**Comment by amee99073** [comment]
We will need to retrieve the FSP_ID for FOM
A forest stewardship plan (FSP) can have one or more FOM (Forest Operations Map)
Currently, FOM are created, FSP ID's are related to those FOM but there is no Referential Integrity to the FOREST_STEWARDSHIP_PLAN.FSP_ID. This validation of FSPs is expected to be done manually by ministry users after FOM are finalized. Validation within the application on creation of the FOM will eventually be required to ensure that the FSP_ID entered actually exists.
Additionally, Forest stewardship Plans are related to Client Numbers in the FSP_AGREEMENT_HOLDER table FSP_ID to CLIENT_NUMBER.  Further validation can be done to ensure the licensee submitting a FOM for the given FSP is, in fact the client of the entered FSP.
Once both CLIENT data and FSP data are available, the data in FOM will be validated and reliable.

**Comment by gormless87** [comment]
Is this a Fingerprint issue, or does it belong as a FOM issue?

**Comment by gormless87** [comment]
Duplicated by #235
