### ISSUE TITLE
Fix for FOM Thick linework

### ISSUE THREAD

**Issue by ArogeG** [bcgov/nr-fom#282]
FOM Thick linework is covering too much of the ground at this scale. This needs to be changed so that the FOM linework symbology at this scale to be changed to be a smaller thickness?

![image.png](https://images.zenhubusercontent.com/62a1029ce9497c39c087ab8b/e147f589-9eb7-4aac-9d18-6b3b00537d1d)

**Comment by ArogeG** [comment]
**Comment from Michelle:** 
With Geoserver and using the Open Geospatial Consortium – web mapping standard - WMS – with the geojson output  .. this styling could be done quite easily with SLDs (Style Line Descriptors) – where you can have scale based styling.. but it would mean hosting the Geoserver java middle ware over top of the postgres database – but it gives you a ton of spatial web mapping flexibility..

As the size of the data grows .. this may help with performance  down the road too. https://docs.geoserver.org/latest/en/user/styling/index.html#styling

**Comment by ArogeG** [comment]
Comment from Julius: This should be implemented relative to the amount of effort required for the fix.

**Comment by ArogeG** [comment]
Basil estimated a story point of about 2+/-.

**Comment by basilv** [comment]
Ian fixed issue with public component, awaiting deploy to test I believe.

**Comment by basilv** [comment]
Confirmed the fix has been deployed to test.

**Comment by basilv** [comment]
I checked FOM public in test and it looks good.

**Comment by ArogeG** [comment]
Waiting on Julius to review and get back to me.
