### ISSUE TITLE
SPIKE: FOM usage reporting

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-fom#317]
Find a solution for getting usage reporting:

how the public is using the FOM public site
how users are founding FOM
FOM usage report

db query, web analytic, open search, google analytics?

https://trainingmodules.nrs.gov.bc.ca/Provincial/IIT/OpenSearchIntro/

https://github.com/bcgov/common-service-showcase/wiki/Logging-to-a-Sidecar

get list or required elements from Julius

Schedule meeting with OneTeam to demo NRIDS Observability

**Comment by DerekRoberts** [comment]
We're a little limited when it comes to data collection.  Google Analytics was allowed for GWells, but they couldn't keep full IP addresses.  Otherwise, seems solid.

**Comment by gormless87** [comment]
1Team Observability (OpenSearch) supports Elastic Common Schema, see detailed field listing https://apps.nrs.gov.bc.ca/int/confluence/display/1TEAM/Common+Schema

**Comment by ArogeG** [comment]
there's an online course for opensearh from one team https://trainingmodules.nrs.gov.bc.ca/Provincial/IIT/OpenSearchIntro/#/

**Comment by basilv** [comment]
Analysis at https://apps.nrs.gov.bc.ca/int/confluence/display/FOM/Citizen+Engagement+Metrics. 
Based on Michelle's direction, I assume we'll be going with OpenSearch.

**Comment by ArogeG** [comment]
@basilv, thanks for putting the document together on Confluence. I would like to schedule a 30 mins call with you to discuss next steps as per: https://apps.nrs.gov.bc.ca/int/confluence/display/1TEAM/Pushing+Data+into+OpenSearch
