### ISSUE TITLE
Spike:  Determine how to insert logs to Opensearch from Openshift

### ISSUE THREAD

**Issue by ArogeG** [bcgov/nr-fom#330]
**Describe the task*
Investigate technical details to transfer logs to OpenSearch for FOM. 
Look into how to setup fluentbit /funbox to move logs from Openshift to OpenSearch as options

- Schedule meeting with OneTeam on the approach in Openshift.

- Review https://docs.fluentbit.io/manual/

- https://github.com/bcgov-nr/nr-funbucks

- Discuss with The Common Showcase Team (Tim Csaky) if required. 

**Acceptance Criteria**
- [ ] Document the process to import logs from OpenSearch
- [ ] https://github.com/bcgov-nr/nr-funbucks
- [ ] third

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by basilv** [comment]
Resources provided by OneTeam:
https://github.com/bcgov-nr/nr-broker/blob/main/src/audit/audit.service.ts#L339
https://github.com/bcgov-nr/nr-funbucks
https://github.com/BCDevOps/nr-apm-stack/tree/master/workflow-cli/configuration-opensearch/index_template

**Comment by basilv** [comment]
Start with nrm-access-external index.
See aws-kinesis.servie.ts in nr-broker
Or just directly use AWS kinesis client library @aws-sdk/client-kinesis
Talking to Kinesis is async non-blocking, but if performance or not losing log files is a priority then still write logs elsewhere (or rely on Fluent.Bit)
Don't send protected B data - field masking is possible. Make sure FOM personal data (public comments) is not logged.

**Comment by basilv** [comment]
Sample log entry in common schema:
{"event":{"category":"web","dataset":"generic.access","duration":12,"kind":"event"},"ecs":{"version":"8.4.0"},"host":{"architecture":"x64","hostname":"NGM500021","os":{"type":"darwin","version":"22.4.0"}},"http":{"request":{"method":"GET"},"version":"1.1","response":{"status_code":200,"mime_type":"application/json; charset=utf-8","bytes":1310}},"labels":{"project":"nr-broker"},"@metadata":{"index":"nrm-test-broker-access-external"},"service":{"name":"nr-broker-backend","environment":"unknown"},"source":{"ip":"::1"},"@timestamp":"2023-04-18T17:41:27.610Z","url":{"original":"[http://localhost:3000/v1/graph/config"},"user_agent":{"original":"Mozilla/5.0](http://localhost:3000/v1/graph/config%22%7D,%22user_agent%22:%7B%22original%22:%22Mozilla/5.0) (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.4 Safari/605.1.15"}}

**Comment by basilv** [comment]
Technical tasks for MVP. I'd put these all into one big story myself. One way to maybe split this into two stories is to get a 'hello world' scenario working where we send existing logs minimally changed to a new temporary index? Not sure how much value that adds though...

1. Determine approach to get FOM API logs to Kinesis. Option 1: use logging 'appender' within Node. Pros: likely far simpler. Cons: might not be able to get logs into required ElasticSearch common schema format thus making solution non-viable. Option 2: write log to file and use Fluent.Bit as sidecar to transform logs into required format and send to Kinesis.
I'm leaning towards looking into Option 1 first to see if viable, falling back to Option 2 if required.

2. Change format of app logs to ElasticSearch common schema. Do this locally (on dev laptop) and send log snippest to OneTeam to validate. 

3. Get Kinesis connection information (URL/etc and service account credentials) from OneTeam and set up log push to Kinesis

4. Test and tweak. View logs in OpenSearch dashboard and assemble widgets that answer business questions.

Post-MVP - look at potentially gathering additional logs (e.g. Caddy) if those can answer more business questions, or add in use of SnowPlow/Google Analytics

**Comment by basilv** [comment]
Seem to be options for converting Nest logs to ECS format - see https://stackoverflow.com/questions/69708256/http-pino-logger-and-elastic-common-schema-ecs-format-in-nestjs
https://gist.github.com/gkampitakis/b36819f38f8886598c20ed1af7245e3a

**Comment by basilv** [comment]
FOM API uses nestjs-pino for logging. This log framework has options for translating log format and sending logs to a different destination (like kinesis). See https://github.com/pinojs/pino/blob/master/docs/transports.md for a general guide (not specific to kinesis unfortunately).

**Comment by basilv** [comment]
Given the lack of explicit support for nestjs-pino logs to go to kinesis in ecs format, the Fluent.Bit option seems slightly better (and has the advantage of greater consistency of approach / support with the rest of the ministry).

**Comment by basilv** [comment]
Technical tasks for Option 2:
1. Create logging volume in openshift configuration, mount in app container.
2. Change pino logger to also write to log file. Likely need log rotation to keep the file size reasonable.
3. Add Fluent.Bit as a 2nd container (sidecar) in the same API pod.
4. Use FunBucks to figure out logging message translation to ecs format locally.

Some helpful tips / examples found at: https://stackoverflow.developer.gov.bc.ca/questions/147

**Comment by paulushcgcj** [comment]
Hi @basilv, openshift save logs into an internal elasticsearch instance, it also have a forwarder to forward logs to external platforms. As OpenSearch is basically elasticsearch, it can be easily integrated. Check this doc [OpenShift Cluster Log Forwarder](https://docs.openshift.com/container-platform/4.12/logging/cluster-logging-external.html)

**Comment by basilv** [comment]
Thanks @paulushcgcj, have you tried this yourself in the BC Gov Openshift cluster?

**Comment by paulushcgcj** [comment]
Is on my bucket list for the next few sprints. Ricardo from SPAR is also researching this topic as well.

**Comment by basilv** [comment]
@ArogeG can this be closed?

**Comment by ArogeG** [comment]
Yes I think so. Closing this now.
