### ISSUE TITLE
FOM Page Forbidden Error 

### ISSUE THREAD

**Issue by ArogeG** [bcgov/nr-fom#332]
**Describe the Bug**
When on the FOM application, I am not able to complete key tasks like save a form after a period of inactivity typically less than 5 mins. 

**Expected Behavior**
The FOM app should be active and the Save form should be active way longer than 5 mins

**Actual Behaviour**
Error message is returned " You were not authorized to perform the request. Please try again.
If this issue persists, try logging out and back in. If this still persists, please contact the service desk."

** Steps To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://fom-test.nrs.gov.bc.ca/admin/not-authorized?loggedout=true
2. Click on Login
3. Login with Business BCeID : LOAD-3-TEST (reach out to Gbola /Catherine for Password)
4. Search for a FOM "Fom 2 Gbola" 
5. Click on **Edit FOM**
4. Wait five mins and navigate from the browser to another application

Error message is returned " You were not authorized to perform the request. Please try again.
If this issue persists, try logging out and back in. If this still persists, please contact the service desk."

**Screenshots**
![image.png](https://images.zenhubusercontent.com/62a1029ce9497c39c087ab8b/5bc808cd-8d25-442f-bee1-380ecc48dae0)
**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge

**Additional context**
![image.png](https://images.zenhubusercontent.com/62a1029ce9497c39c087ab8b/4275d4e9-d3e0-46b9-a733-89f10d4bc245)

**Comment by ianliuwk1019** [comment]
I can reproduce in general.
Looks like It's frontend issue on refreshed token is missed for next request.
Frontend got 403 => reached out to Cognito for refresh token => did receive new token => did the original request to server again but again fail with 403.
![image.png](https://images.zenhubusercontent.com/62a9ff93d8506f14758ef03a/5b94fce9-24bb-444c-aefa-b3c9b5fa0228)
![image.png](https://images.zenhubusercontent.com/62a9ff93d8506f14758ef03a/b687d8d9-6091-4c7a-9250-b10c80136a36)
