### ISSUE TITLE
Integration of Keycloak Redirects into Pipeline - Add Redirect

### ISSUE THREAD

**Issue by franTarkenton** [bcgov/nr-fom#35]

**Comment by basilv** [comment]
What's GHA?

**Comment by DerekRoberts** [comment]
@basilv GitHub Actions

**Comment by franTarkenton** [comment]
Added [redirect action](https://github.com/bcgov/nr-keycloak-redirect) to the fom pipeline.  In testing the action is consistently raising the following error:
`/bin/bash: ./entrypoint.sh: No such file or directory`

Able to run the image locally without problems:
```
docker pull ghcr.io/bcgov/nr-keycloak-redirect/kc-manage-redirect:20220623-2043
docker run -it ghcr.io/bcgov/nr-keycloak-redirect/kc-manage-redirect:20220623-2043
```

Logging into the container shows the entry point exists:
```
docker run -it --entrypoint /bin/bash ghcr.io/bcgov/nr-keycloak-redirect/kc-manage-redirect:20220623-2043
bash-5.1# ls -la entrypoint.sh
-rw-r--r--    1 root     root           282 Jun 23 20:43 entrypoint.sh
bash-5.1#
```

going to try removing the relative path from `./entrypoint.sh` to `/entrypoint.sh`

**Comment by franTarkenton** [comment]
In summary, when containers are run in a github action, relative paths seem to cause problems.

Waiting till monday for Derek to return / provide review so the rest of the pipeline can run.

[link to the pr](https://github.com/bcgov/nr-fom/pull/67)

**Comment by franTarkenton** [comment]
https://github.com/bcgov/nr-fom/pull/67 

-  successfully added the keycloak redirect
