### ISSUE TITLE
Implement PubCode for FOM

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-fom#351]
**Describe the task**
Add Pubcode to FOM repo

**Acceptance Criteria**
- [ ] All of the mandatory Sections/Fields on the data entry form are populated correctly

**Additional context**
- JSON schema for bcgovpubcode.yml: bcgovpubcode.yml is a metadata standard for repositories containing software developed or acquired by the Public Administration, aimed at making them easily discoverable and thus reusable by other entities.
- Form to enter metadata: https://pubcode.apps.silver.devops.gov.bc.ca/form
- Source repo (see readme) : https://github.com/bcgov/pubcode

**Comment by gormless87** [comment]
With all mandatory fields completed the yml is:

---
data_management_roles:
  data_custodian: TBD
  product_owner: Pete Tollestrup
product_external_dependencies:
  notification_standard: []
product_information:
  api_specifications: []
  ministry:
    - Water, Land and Resource Stewardship
  product_acronym: FAM
  product_description: >-
    The Forest Access Management (FAM) is a foundational product for other FSA
    apps. FAM will provide the opportunity for government staff  and external
    stakeholders to provision access to forestry suite of applications. FAM is
    being hosted on the AWS cloud in the Canada  Region and is managed by the
    SSO Cloud Pathfinder team.  FAM uses an Open ID Connect (OIDC) standard for
    safe and transparent  authentication. The purpose of this initiative is to
    provide a system where access privileges can be assigned to internal and
    external users of Forestry Suites of Application (FSA) systems.
  product_name: Forest Access Management
  product_status: active
  product_urls: []
  program_area: FSA
product_technology_information:
  backend_frameworks: []
  backend_languages_version: []
  frontend_languages: []
  hosting_platforms:
    - Amazon-Web-Services
version: 1

**Comment by gormless87** [comment]
[https://app.zenhub.com/files/493404403/d85825d9-52c7-4dcc-9538-964405bbe250/download](https://app.zenhub.com/files/493404403/d85825d9-52c7-4dcc-9538-964405bbe250/download)

It's really a yml file, but had to change the extension to upload

**Comment by basilv** [comment]
@gormless87 Not sure about data custodian - I put Julius. Otherwise I filled out the info as per below:
---
data_management_roles:
  data_custodian: Julius Huhs
  product_owner: Pete Tollestrup
product_external_dependencies:
  identity_authorization:
    - IDIR
    - Business-BceId
    - BCGov-SSO-Keycloak
  notification_standard:
    - Common-Hosted-Email-Service
product_information:
  api_specifications:
    - https://fom.nrs.gov.bc.ca/api/
  ministry:
    - Forests
  product_acronym: FOM
  product_description: >-
    Division 3.1 of Bill21-Forest and Range Practices Amendment Act requires
    Forest Stewardship Plan holders to make a Forest Operations Map available
    for public review and comment. Public engagement in the management of Crown
    resources is encouraged and this site offers a platform for members of the
    public to submit comments for consideration.
  product_name: Forest Operations Map
  product_status: maturing
  product_urls:
    - https://fom.nrs.gov.bc.ca/public/
    - https://fom.nrs.gov.bc.ca/admin/
  program_area: Forest Science, Planning, & Practices Branch
product_technology_information:
  backend_frameworks:
    - name: NestJS
      version: '10'
  backend_languages_version:
    - name: TypeScript
      version: '4.8'
  ci_cd_tools:
    - GitHub-Actions
  data_storage_platforms:
    - Postgis
    - Postgresql
    - Object-Storage
  frontend_frameworks:
    - name: Angular
      version: '15'
  frontend_languages: []
  hosting_platforms:
    - Private-Cloud-Openshift
  spatial_mapping_technologies:
    - Leaflet
version: 1

**Comment by gormless87** [comment]
PubCode should match IRS:

Ministry:
Forests (I have updated IRS)

Description:
A FOM is a prerequisite to requesting a forest tenures permit by a Licensee. The FOM is publicized via media (newspaper, on-line and physically posted) to notify potentially impacted and interested stakeholders of the Licensee’s intent to request a forest tenures permit. A FOM must show the approximate locations of proposed roads and cut blocks; and must undergo a review and comment process by interested parties, including Indigenous Nations, before the holder of a FSP can request a cutting permit or a road permit. The FOM allows for the capture of stakeholder and other 3^rd^ parties input to the proposed tenures as well as captures the Licensee’s response and/or actions to input received. The FOM Report must accompany the permit application and must significantly match the area delineated on the permit application as the Area of Interest as well as contain all stakeholder comments and Licensee responses/actions as part of the permit.

data custodian from BCDC (I will update IRS when I get access to do so)
Name
Rachael Pollard
Email
Rachael.Pollard@gov.bc.ca
Organization
Forest Science, Planning and Practices Branch
Role
Custodian
