### ISSUE TITLE
FOM: endpoint getFileContents() for downloading attachment not working

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-fom#353]
**Description:**
While working on ticket #158 testing out using new backend api NestJS Guard implementation for controllers, found there is a problem for **AttachmentController.getFileContents()** endpoint.
Initial investigation identifies that this bug isn't introduced from backend work at #158; it was already not working before FOM Angular upgrade.

This particular endpoint allows **admin** users to download attachments (for example, at "View FOM") page.

At the current production (I used a PR dev deployment without new code change, same as current main code for production) this endpoint will throw "500" internal error. With current backend api work using Guard for endpoint, this guard for this endpoint will return "403" error, which make more sense as the problem seems to be no header included in the request but endpoint is secured. Why the header is missing on this particular endpoint requests still needs investigation. Currently, it seems the problem is from frontend.

![image.png](https://images.zenhubusercontent.com/62a9ff93d8506f14758ef03a/14572946-4a83-4081-bdb0-2b57c2a3bb0b)

**Acceptance Criteria**
- [ ] "Admin" client user can download the file content.
- [ ] Ministry user can download the file content.
- [ ] No public access for file content download.

**Additional context**
- Probably need to re-write 'admin' frontend code to use api (not just click a link) to include 'auth' header in request for file download.

**Comment by basilv** [comment]
I've tested this as part of FOM upgrade testing and confirmed that both public notices and supporting document attachments suffer from this problem. This is a major issue. One quick fix would be to drop the need to secure access to public notices, and only secure the supporting documents. But still need a solution for FOM admin to view supporting documents in secured fashion though...

**Comment by basilv** [comment]
Confirmed that Stakeholder engagements (interactions) attachments are also experiencing the same problem.

**Comment by ianliuwk1019** [comment]
It looks like we might need to do getFileContents for backend api according to NestJS: [streaming-file](https://docs.nestjs.com/techniques/streaming-files).

**Comment by ianliuwk1019** [comment]
While working on this issue and testing "public" side to download file, encountered strange 403 error even though backend permitted "public" to access the endpoint. Investigation found that one of the backend Attachment Entity property (attachmentTypeCode) is undefined, so the check for `isViewAuthorized` failed.
It is strange the entity is missing the value from TypeORM for `attachmentTypeCode` but has value for `attachmentType` relation from (findOne()); but the same entity with the same decorator `@RelationId` is used for `projectId` and has a value. Don't know why it behaviour differently.

However, I am able to work around the issue.
![image.png](https://images.zenhubusercontent.com/62a9ff93d8506f14758ef03a/8be6184e-649a-4f63-84a9-d4af8ac13138)
