### ISSUE TITLE
Adding period of operations to FOM Details

### ISSUE THREAD

**Issue by basilv** [bcgov/nr-fom#360]
The period of operations (start/end) fields previously added to just public notice need to be added to the 'main' FOM - so added for entry to the create/edit FOM screens, and displayed on the public side as part of the FOM Details. 

These fields will no longer be listed/editable on the public notice screen.

Same logic will be kept for these fields - start operations year defaults to current year, max end operations year 7 years out, just year field is fine.

Acceptance Criteria:
- pre-existing periods of operation on public notice are kept (not lost)
- period of operations appears under FOM Details on FOM public
- period of operations appears under Create/Edit FOM screens on FOM Admin
- same logic as before for editing period of operations

**Comment by basilv** [comment]
Deadline: before Jan 1, 2024 but ideally earlier. No real time pressure right now.

**Comment by basilv** [comment]
Will want to migrate the columns from the public-notice table to the project table as part of this work.

**Comment by basilv** [comment]
Questions for Julius:
1. For data migration if the existing FOM has no public notice and thus no period of operations, what to do. Assumption: leave period of operation blank.

**Comment by basilv** [comment]
Questions for Julius:
1. For data migration if the existing FOM has no public notice and thus no period of operations, what to do. Assumption: leave period of operation blank.

**Comment by MCatherine1994** [comment]
currently in production, there are 4 public notice, only 1 has the operation period information, should be safe enough to do the clean up once we confirmed the data migration is successful

**Comment by MCatherine1994** [comment]
Will merge the business requirement feature first, and verify if everything works as expected in test. And then open a new pull request to remove the two operation columns in the public notice table
