### ISSUE TITLE
Trivy security warnings not automatically closing.

### ISSUE THREAD

**Issue by basilv** [bcgov/nr-fom#364]
Just looking at the FOM repo - security alerts - two questions
1. Looks like all the dependabot alerts have resolved, not sure if this is because dependabot is totally turned off and its all just renovatebot.
2. There are still obsoleted code scanning alerts from trivy that didn't get automatically cleaned up. (Some are really old from 2022.) I assume the trivy alerts need to be manually dealt with and don't auto-close?
Derek Roberts — Yesterday at 2:38 PM
1. Hooray! Good for you and Ian. 😄
I'll make sure Dependabot is still doing security alerts. That part should still be active.
2. Not sure. Can you please point me to them? Link?
basilv — Yesterday at 4:06 PM
Thanks! Mostly Ian.
Here's an example of #2: https://github.com/bcgov/nr-fom/security/code-scanning/2
Derek Roberts — Yesterday at 4:18 PM
That's weird! It even says fixed.
Would you mind ticketing me to investigate? To make sure this is staying up to date. 
I'm off work to do renos and not by the computer now!

**Comment by DerekRoberts** [comment]
There was a duplicate stale Trivy configuration!  Removed.  Hopefully this is solved.  :)
