### ISSUE TITLE
Add link to training video on FOM Admin post-login

### ISSUE THREAD

**Issue by basilv** [bcgov/nr-fom#382]
A training video has been created for users of FOM Admin. Julius wants a link to this training video made available within FOM Admin, after login is completed.

In initial discussions with Olga and Julius, the thought was to put it at the top of the Search FOMs screen (which is displayed by default after login). Putting at the bottom of the screen (after search results) would be another option. Or could create a Help page? Julius didn't seem to have a strong opinion.

This is blocked waiting for the video link to be provided by Julius. 

A decision (at least preliminary) should be made regarding where to put the training video link before this is pulled into a sprint.

**Comment by OlgaLiber2** [comment]
@basilv  do we have a link from Julius now?

**Comment by basilv** [comment]
I don't recall getting it.

**Comment by OlgaLiber2** [comment]
@basilv @gormless87 I'm closing this tickets. Links to videos have been updated.
