### ISSUE TITLE
Renovate babysitting

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-fom#425]
**Describe the task**
Address renovate PR's in a timely manner. Clear communications with DevOps Specialist.

**Acceptance Criteria**
- [ ] All PR's accepted and implemented OR declined

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by ianliuwk1019** [comment]
For Sprint Jul 20 - Aug 09, 2023:
* Basil verified and merged: [Snyk] Security upgrade aws-amplify from 5.3.0 to 5.3.2 [#423](https://github.com/bcgov/nr-fom/pull/423)
* fix(deps): update dependency remeda to v1 [#414](https://github.com/bcgov/nr-fom/pull/414) merged.
* fix(deps): update dependency helmet to v7 [#413](https://github.com/bcgov/nr-fom/pull/413) merged.

Closed with comment:
* fix(deps): update dependency @nestjs/cli to ~10.1.0 [#420](https://github.com/bcgov/nr-fom/pull/420).
