### ISSUE TITLE
Reduce requested cpu and memory resource in FOM openshift deployment config

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-fom#430]
**Describe the Task**
In the openshift deployment config, we don't need that much cpu and memory resource, reduce those numbers in the deployment config could save the platform service team some resources.

![Screen Shot 2023-07-20 at 1.58.34 PM.png](https://images.zenhubusercontent.com/6201a0f0c6815e7dfafa3f78/58220344-9264-4b28-a455-edb0f16a2208)

**Acceptance**
- In each the openshift deployment config yaml file, update the request cpu and memory to a lower number, CPU request could change to 30m, Memory request could change to 0.3Gi

**Comment by ianliuwk1019** [comment]
DEV/TEST/DEMO to low request cpu and memory for not wasting platform resource. PROD can set to higher (if needed).

**Comment by basilv** [comment]
FOM Database deployment config looks like it is entirely missing request/limit settings (or just using defaults) - the limit of 0.25 CPU is most likely far too low.

API/Public/Admin can be sized down, especially public/admin as they are using caddy now.
