### ISSUE TITLE
Deploy FOM to production on Jul 25

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-fom#435]
Create a new release for FOM to production. We don't have the release please in FOM, so will just trigger the pipeline to deploy production from the current main branch. This latest commit is [f7b743e](https://github.com/bcgov/nr-fom/commit/f7b743e8a0c302438918880d994ddadb76c88b99).

Release note on Jul 25, 2023:
- feat: [#210](https://github.com/bcgov/nr-fom/issues/210) support pbn post before commenting open [#393](https://github.com/bcgov/nr-fom/pull/393)
- feat: [#360](https://github.com/bcgov/nr-fom/issues/360) add operation period in FOM details [#411](https://github.com/bcgov/nr-fom/pull/411)

- fix: [#371](https://github.com/bcgov/nr-fom/issues/371) FOM (admin) - Updating Stakeholder Engagement is Causing Issue to Backend Date(s) Validation for Selected Date on Commenting Open Date. [#370](https://github.com/bcgov/nr-fom/pull/370)
- fix: [#353](https://github.com/bcgov/nr-fom/issues/353) get file content sec access [#381](https://github.com/bcgov/nr-fom/pull/381)
- fix: api not up when using docker-compose to run [#383](https://github.com/bcgov/nr-fom/pull/383)
- some packages upgrade
- fix: change Renovate prConcurrentLimit=3 [#419](https://github.com/bcgov/nr-fom/pull/419)
- fix: [#210](https://github.com/bcgov/nr-fom/issues/210) Feedback on Early Public Notice Publishing Date [#422](https://github.com/bcgov/nr-fom/pull/422)
- fix: [#426](https://github.com/bcgov/nr-fom/issues/426) Notice publish date warning and adjustment disable date picker manual input [#431](https://github.com/bcgov/nr-fom/pull/431)
- fix: [#427](https://github.com/bcgov/nr-fom/issues/427) Days Remaining adjustment [#432](https://github.com/bcgov/nr-fom/pull/432)

Release process:
- Approve the prod deployment for the latest one under the pipeline "Merge to Main"
- Approve the cerbot step once the  prod deployment step finished
- Once all steps are done, verify if all FOM production sites are up and new changes are there
- Create a "demo" branch from the main branch, this will trigger the "Merge to Demo" pipeline and do the demo deployment
- Once the pipeline is finished, verify if all FOM demo sites are up
- Delete the "demo" branch

**Comment by gormless87** [comment]
Thanks @MCatherine1994, this looks great.
