### ISSUE TITLE
Warning Pop-up required for Publish and Finalize Action

### ISSUE THREAD

**Issue by amee99073** [bcgov/nr-fom#44]
Two new pop ups to minimize user errors we've observed: 

1. Add a warning pop up  when publishing a FOM. 

Use this wording approved by Julius: 
"Publishing your FOM will make it viewable to the public once commenting opens, and you will not be able to make any edits. Do you want to proceed"? @MCatherine1994 

@MCatherine1994 Wording for finalizing a FOM, approved by Julius: 
“Finalizing your FOM will send a notification to district staff, and lock the FOM, so you will not be able to make any changes. Do you want to proceed?”

From Jira FOM-120

**Comment by MCatherine1994** [comment]
fyi.... maybe we already have a popup for finalized, double check for it

![Image](https://github.com/bcgov/nr-fom/assets/23131735/bdc14c28-0f65-477b-8c6f-f1da552e320f)

**Comment by MCatherine1994** [comment]
fyi, we have a popup when finalize FOM

![Image](https://github.com/bcgov/nr-fom/assets/23131735/cc920e74-1c40-4eac-8195-7bd31019db67)
