### ISSUE TITLE
Implement requirements for mandatory Timber Sales Manager name on BCTS FOM's

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-fom#448]
**Describe the task**
There is a legal requirement to display the BCTS timber sales manager's name on BCTS FOMs.

Logic: when forest client name starts with "TIMER SALES MANAGER" then entry of Timber Sales Manager field (in Create/Edit FOM screen) is mandatory.  Otherwise optional (to be safe, business doesn't require it at all except for BCTS FOM's where its mandatory)

This Timber Sales manager field will be displayed in FOM Public under the Details.
Does NOT need to be displayed on the public notice.

**Acceptance Criteria**
- [x] new field to enter Timber sales mgr name
- [x] only enabled for BCTS FOM's

**Additional context**
- name display on public interface details section
- name not required on the notice 
- may be able to determine whether or not it is a BCTS FOM based on forest client naming convention

**Comment by ianliuwk1019** [comment]
This does not seem to have complex logic.
The work is outline below:
```
Backend:
	* Add a new varchar(nullable) column, BCTS_MANAGER_NAME, into table app_fom.project.
	* Add a new field(bctsMgrName) into project entity.
	* Add a new field(bctsMgrName) to controller's create project endpoint request object with necessary annotation or validation.
	* Add a new field(bctsMgrName) to ProjectResponse object for frontend display.
	* Generate api-client.

Admin:
	* Add an input field (Timber Sales Manager Name) in "Add New FOM" or "Edit FOM" page.
	* New field is "Required" for BCTS FOM. This is when forest client name starts with "TIMBER SALES MANAGER" 
	* Requirement did not specify, but maybe limit length to 50 for this name field.
	* Display Timber Sales Manager Name on "View FOM" detail page below "FOM Holder".
	
Public:
	* Display "Timber Sales Manager Name" on FOM Detail under "FOM Holder".
	
```

**Comment by ianliuwk1019** [comment]
We can start implement this (new ticket required? or reuse this one?).

**Comment by basilv** [comment]
@ianliuwk1019  I added a few clarifications to your writeup. Limiting name length to 50 is fine.

**Comment by ianliuwk1019** [comment]
Move back to in-progress to use the same ticket for implementation.
