### ISSUE TITLE
Update link to the FOM Website in the Public and Admin site

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-fom#449]
**Describe the task**
Got the requirement from Julius: 
Please update the link to the FOM Website in the Public interface. Below is the correct link, so please update the button.

https://www2.gov.bc.ca/gov/content/environment/natural-resource-stewardship/laws-policies-standards-guidance/legislation-regulation/forest-range-practices-act/frpa-improvement-initiative/forest-operations-map

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBckV4IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c7925096be75cce84deb8e8e8a5b74ef6c5cfd86/image.png)

I would also like to add the links to the online training modules to the first page of the Admin Interface, so if possible, please add two buttons:
 
Training for FSP Holders (Submitters): https://trainingmodules.nrs.gov.bc.ca/provincial/for/FOMtrainingFSP/index.html#/
Training for Reviewers: https://trainingmodules.nrs.gov.bc.ca/Provincial/FOR/FOMReviewers/index.html#/
 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBck14IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2a6e58688f57b0d2d974f1c2295b1c3d94d38a44/image.png)

**Acceptance Criteria**
- [x] Update the link to FOM website on Public site
- [x] Add required training buttons on Admin site
- [x] Additional adjusted both Public/Admin headers.
- [x] Additionally made both Public/Admin font-family/font-size matching each other.

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by ianliuwk1019** [comment]
Hello @OlgaLiber2 ,
The first link is very easy to change but I didn't know there are two other links for Admin site. Admin does not have the "**About**" page like Public site has. I can't seem to find a good place to put the two links in first page of Admin interface. Do we want to discuss with Julius (not sure when the meeting is...). Thanks. @MCatherine1994

**Comment by OlgaLiber2** [comment]
@ianliuwk1019 @MCatherine1994 new mockup pending Julius' feedback
![Capture-fom-training-page](https://github.com/bcgov/nr-fom/assets/121979429/2acbaf4f-4921-4be3-83a4-c4106d5cce24)

**Comment by OlgaLiber2** [comment]
@ianliuwk1019 changes approved by Julius. Please add the following wording to the subheadings: 

Training for FSP holders
Online course to create, administer and submit FOMs in the admin interface

Training for FOM reviewers (District staff)
Online course to review and administer FOMs in the admin interface


If possible, please incorporate changes to the header in this ticket. Thank you. 
*please note, the changes to the header need to be implemented on all screens and all environments.

**Comment by OlgaLiber2** [comment]
@ianliuwk1019  also when you are adjusting the header, can you please make sure the title on the left is centered vertically. [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWtiQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--374874ac431c9935c0eb17fe89ec0366a2d392f3/Capture-headertitle.PNG)

**Comment by ianliuwk1019** [comment]
Hi @OlgaLiber2 
I think in the past, that was probably meant to be position like that; but if preferred now, I can adjust that to be centered.
Probably it does not matter, but users might notice difference from previous training document on layout change.
I will do all the header adjustment mentioned, just might a bit slow since I usually have trouble with css, give me a bit time.

One small thing, the "user" display name will be at the end, rather than besides the vertical bar (action item).

**Comment by OlgaLiber2** [comment]
thanks @ianliuwk1019! Is it possible to have the "logout" action at the very end instead of the user name? It makes more sense.  Also we can drop FOR:EX extension on the user name and just keep the first and last name

**Comment by OlgaLiber2** [comment]
@ianliuwk1019 and can we capitalize "Test" please. 
![Capture-test](https://github.com/bcgov/nr-fom/assets/121979429/2cd817e3-89b0-4dfd-925e-90b5e211d223)

**Comment by ianliuwk1019** [comment]
Hi @OlgaLiber2 , Sure I can try. What I meant was the items on headers (at the right) are clickable links(html unordered list \<a> tag), but then "Julius" is a text(html \<span>), then come again with another clickable logout link (\<a> tag). Normally, among the vertical bar items are all "action(clickable)".
But don't make your decision just yet. I will try.

I won't be able to change it to "first name, last name" the **model** does not yet support for that (or may need some more work to get it). For now the model returns to frontend available as "userName" (probably is the id) or "displayName".

**Comment by OlgaLiber2** [comment]
@ianliuwk1019 Got it. OK, let me know if it works out.

**Comment by ianliuwk1019** [comment]
Hi @OlgaLiber2 , The code changes are ready. It will be reviewed in PR.
While it is in review, you can peak the FOM deployed at PR(dev) stage here, see if they are ok for you.
Additionally, I found a small issue and fixed public menu toggling for small device.

public: https://fom-40.apps.silver.devops.gov.bc.ca/public
admin: https://fom-40.apps.silver.devops.gov.bc.ca/admin

**Comment by OlgaLiber2** [comment]
@ianliuwk1019 will do. I don't have access to https://fom-40.apps.silver.devops.gov.bc.ca/admin
can you grant me access please?

**Comment by OlgaLiber2** [comment]
@ianliuwk1019 looks good!! Juat a few minor tweaks: 

- can we make the username display in white? I'm not sure why it's gray 
![Capture-fom-edits](https://github.com/bcgov/nr-fom/assets/121979429/6965ce33-b719-4b88-a234-0f08e4a34946)

- what is "40" on the nav bar? 

- the font on the header looks different on the public page and the admin portal. Can we make the font type + font size the same as it is in the admin portal on the public portal as well?

**Comment by ianliuwk1019** [comment]
Hi @OlgaLiber2 ,
* Because we mixed the **action item** with name in between, I purposely use light grey color for the user name as it isn't a clickable link and would make user confused that's a link to click. Please let me know if you still like to make it white or want to discuss with Julius more on this.
* (40) is just an environment display, in Dev it is PR number, you don't need to pay too much on that, it is for developers and also Julius knows its environment. Production won't have that.
* I do notice the font seems a slightly different, I was already trying to figure out that yesterday but didn't quite get why. I can spend more time if you wish but not sure if I can find the issue. However, the font and size look for both sites are still the same as what we have in Production so it wasn't due to the change this time.

**Comment by OlgaLiber2** [comment]
@ianliuwk1019 ok. Keep the username as you have it then. Everything else looks good too. Please look into making the font type + font size the same for public and admin sites. Other than that it looks good 🙌

**Comment by MCatherine1994** [comment]
Just paste the training link Julius shared with us from GitHub here: https://bcgov.github.io/forestry-digital-services/assets/training/fom/#/

**Comment by ianliuwk1019** [comment]
Thanks Catherine! This is updated again on the PR code based now.

**Comment by ianliuwk1019** [comment]
PR is merged and deployment is done in TEST environment.
[Public: https://fom-test.nrs.gov.bc.ca/public/projects#splash](https://fom-test.nrs.gov.bc.ca/public/projects#splash)
[Admin: https://fom-test.nrs.gov.bc.ca/admin](https://fom-test.nrs.gov.bc.ca/admin)
@OlgaLiber2 @gormless87

**Comment by gormless87** [comment]
@ianliuwk1019, @OlgaLiber2 - the changes look good to me. The training links work and I believe the text/font changes  are OK as well.

**Comment by OlgaLiber2** [comment]
@ianliuwk1019 looks good to me too. Can we push these changes to prod? Once it's in prod, I'll let Julius know. He's seen the changes already and is good with it. @gormless87

**Comment by ianliuwk1019** [comment]
Thanks for verifying Pete and Olga.
Changes are deployed to PROD and DEMO.

Demo Links:
- Public: https://fom-demo.apps.silver.devops.gov.bc.ca/public
- Admin: https://fom-demo.apps.silver.devops.gov.bc.ca/admin/search

PROD Links:
- Public: https://fom.nrs.gov.bc.ca/public
- Admin: https://fom.nrs.gov.bc.ca/admin/search

@OlgaLiber2 @gormless87 @basilv
