### ISSUE TITLE
Increase email address field length

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-fom#464]
**Describe the task**
•	In the Online Public Notice section, the maximum allowable number of characters for the email address is one character too short for the default email that we were planning to use.  Is it possible to increase the allowable character limit at all?  The email we were instructed to use is rather long, so we had requested an alternative that was easier to use.  But there seems to be some resistance to that idea.  We’ll keep pushing.

**Acceptance Criteria**
- [ ] email address field increased FROM [ ] TO [ ]
- [ ] second
- [ ] third

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by ianliuwk1019** [comment]
Looks like this is only the frontend change if current 50 char(s) is 1 char too short.
The backend has a limit on 100 char(s), but for some reason frontend html has limit on 50 char(s).
Will use 100, hope it is ok.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbGorIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f1b1509f1b053b0a72486601ba191f5be769e3a6/image.png)
@basilv

**Comment by basilv** [comment]
100 characters is fine, just double check that a longer email will display okay (e.g. no weird wrapping / layout issues).

**Comment by gormless87** [comment]
In TEST is see a very long email:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMU1OQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--afdbac6d983ce17011eab9379927bab70614d0b4/image.png)
