### ISSUE TITLE
FOM  Front-end: Integration with FAM

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-fom#47]
Current FOM login uses KC; transition to FAM auth via Cognito

Prerequisite: FAM MVP will need to be in production before the FOM integration with FAM can go to production.

Activities:
1. Change FOM Admin front-end to use login page provided by FAM.
2. Change FOM Admin front-end parsing of JWT token.

--
3. (moved to FOM #280 ) Change FOM API back-end decryption of JWT token to use FAM certificate.
4. (moved to FOM #280)Change FOM API back-end parsing of JWT token.
5.-- (FAM issue #314). Set up Julius as FOM app admin in FAM
6. --(FSM issue#104 ): Migrate all FOM users to FAM

**Comment by MCatherine1994** [comment]
reference reading:   
https://enlear.academy/5-step-guide-for-user-authentication-using-angular-amplify-and-aws-cognito-hosted-ui-a616e10efed3. 
https://aws.amazon.com/blogs/mobile/use-existing-cognito-resources-for-your-amplify-api-storage-and-more/

**Comment by MCatherine1994** [comment]
Need to add redirect callback urls for FOM client in FAM `infrastructure/server/oidc_clients_fom.tf`

**Comment by MCatherine1994** [comment]
Updated the logout url chain back to site minder

so the logout url = "siteminder logout_url and its returl=" + "Keycloak logout url and its post_logout_redirect_uri=" + "conginito logout url and its logout_uri=" + "app logout url"

**Comment by ianliuwk1019** [comment]
Thanks Catherine for setting this logout up from what we understood after discussion with Conrad.

The logout chains is a known issue (on SSO Stackoverflow board) between for IDP providers (Siteminder, Keycloak). Hopefully later we can find a way for Cognito to handle the logout (not sure if possible) for the future clients (apps).
The current logout for FOM (local/dev) becomes like this:
```
 https://logontest7.gov.bc.ca/clp-cgi/logoff.cgi?retnow=1
	&returl=https://dev.oidc.gov.bc.ca/auth/realms/ichqx89w/protocol/openid-connect/logout
	?post_logout_redirect_uri=dev-fam-user-pool-domain.auth.ca-central-1.amazoncognito.com/logout?client_id=6c9ieu27ik29mq75jeb7rrbdls
	&logout_uri=http://localhost:4200/admin/not-authorized?loggedout=true
```
As currently when integrating FOM with FAM, even though "FOM" does not directly contact Keycloak and Sitemider (after integration to FAM/Cognito), to logout, "FOM" still needs to configures these settings just for logout purpose. This seems quite strange to me. Later app which is going to integration with FAM will have the same question.
@ArogeG

**Comment by ArogeG** [comment]
To be tested with 280 after deployment.
