### ISSUE TITLE
Text update in bottom of all FOMs

### ISSUE THREAD

**Issue by OlgaLiber2** [bcgov/nr-fom#476]
**Describe the task**
In order to accurately reflect the regulation, some minor changes to the text displayed at the bottom of all FOMs is required. Please replace the existing text with:

_This_ FOM can be relied upon by the FOM holder for the purpose of a cutting permit or road permit application, until the date three years after commencement of the public review and commenting period. FOMs published by BC Timber Sales can be relied upon for the purpose of a cutting permit or road permit application, or the issuance of a Timber Sales License until the date three years after conclusion of the public review and commenting _period._

**Acceptance Criteria**
- [x] text is updated

**Additional context**

**Comment by OlgaLiber2** [comment]
[Uploading... Capture-fom text change.PNG]

**Comment by ianliuwk1019** [comment]
This is deployed on FOM Test environment. @gormless87
