### ISSUE TITLE
Enable “mouse wheel zoom” 

### ISSUE THREAD

**Issue by OlgaLiber2** [bcgov/nr-fom#477]
**Describe the task**
Enable “mouse wheel zoom” on the detailed map page in the public interface, rather than having to click the + and – buttons.

**Acceptance Criteria**
- [x] mouse wheel zoom is enabled
- [x] using Leaflet capability 

**Additional context**
[Uploading... mouse wheel zoom.png]

**Comment by gormless87** [comment]
[Uploading... image.png]

**Comment by ianliuwk1019** [comment]
Basil provided this ref: https://gis.stackexchange.com/questions/111887/leaflet-mouse-wheel-zoom-only-after-click-on-map

**Comment by ianliuwk1019** [comment]
This is deployed on FOM Test environment. @gormless87
