### ISSUE TITLE
Check Status of Entrust Certificates - FOM

### ISSUE THREAD

**Issue by franTarkenton** [bcgov/nr-fom#48]
Entrust Certificates were created using Certbot approximately 1 year ago.  The update emails are configured to go to the FOM-ADMIN email.  Currently not sure who has access to this email, and started thinking that someone should check this, thus this ticket

This ticket involves determining when the exact date of expiry is and ensuring that the appropriate steps are being taken to renew the certificates.

**Comment by franTarkenton** [comment]
FOM - PROD certs expire on 2022-08-09.
FOM - TEST certs expire on 2022-07-14 

@gormless87  - expiry dates above ^^^

**Comment by gormless87** [comment]
@franTarkenton is this issue in progress?

**Comment by franTarkenton** [comment]
@gormless87 Yes this is in progress!  Closing this ticket, created a new ticket https://github.com/bcgov/nr-fom/issues/48 to track the work associated with PROD... and this ticket https://github.com/bcgov/nr-fom/issues/61 describes the work that has been done in TEST.
