### ISSUE TITLE
Work with Derek to update the Openshift deployment pipeline for dev urls

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-fom#480]
**Describe the task**
Work with Derek to update the openshift deployment pipeline for dev urls. Check the example in FOM [#475](https://github.com/bcgov/nr-fom/pull/475/files) to set the deployment number in the range 0-49. 

**Acceptance Criteria**
- [x] Update the pipeline for FOM

**Additional context**

**Comment by ianliuwk1019** [comment]
Catherine has done the 0-49 supports for FOM pipeline; and the work is merged.
Will close this one.
