### ISSUE TITLE
Enable the Timber Sales Manager name field if the applicant is BCTS.

### ISSUE THREAD

**Issue by ianliuwk1019** [bcgov/nr-fom#488]
**Describe the task**
For FOM "Timber Sales Manager name" field, only show the field when it is BCTS FOM, if not hide the field.

**Acceptance Criteria**
- [x] Conditionally show (when Holder matches Timber Sales Manager...) "Timber Sales Manager name" field and hide otherwise .
- [x] On display side (admin/public frontend), only show this field if value present.

**Comment by gormless87** [comment]
Looks good
