### ISSUE TITLE
Strange Tests Failure When Some Dependency Upgraded for API

### ISSUE THREAD

**Issue by ianliuwk1019** [bcgov/nr-fom#544]
This was first discovered when there was a security PR open #501. The PR had some security override and some dependencies update on all projects for FOM especially in `api`.
<img width="962" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNldZQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9e3a2d0538da727b3de67d5bf07adf4c655809cf/image.png" alt="image.png" />

Checking out the same PR branch running locally, the tests failed too (can be reproduced). And when switching back to main branch reinstall package (remove node_modules), run the tests, the tests pass.

There are two tests failure in this way on "project.service.spec.ts":
* <img width="1229" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnlZQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ca09728bbd9ba164d18f1d039dcfac0956054bd8/image.png" alt="image.png" />

* <img width="1247" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjJZQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c4d489c74957db78ccbabdba3057560a8e88bbdc/image.png" alt="image.png" />

This is a strange one, and needs to be investigate further, this might (or depends on what package being upgraded, not clear yet) soon impact pipeline run.

**On side note:**
* When checking out main branch (from which run tests pass) and "just" install latest **jest** package, the same failure will show up in local when running tests.
<img width="1201" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0tZQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5cec6093042c953836c319310b29d271841caa06/image.png" alt="image.png" />

* It's probably not related but a test failure ticket in the past at FOM probably also needs to be taking care of too: #440

**Comment by DerekRoberts** [comment]
Looks like this is related to subdep @babel/traverse, which has @babel/generator, @babel/helper-split-export-declaration and @rridgewell/gen-mapping as further deps.

**Comment by MCatherine1994** [comment]
solved in pr #548
