### ISSUE TITLE
End of Operations Year initial pick for the same year of Start of Operations shows wrong error message.

### ISSUE THREAD

**Issue by ianliuwk1019** [bcgov/nr-fom#553]
**Describe the Bug**
There is a bug on showing validation error message on **"End of Operations"** year .
When adding a new FOM, picking a year from "End of Operations" field with the same year as **"Start of Operations"** field should not show message: **"Must be equal to or later than the Start of Operations"**.

<img width="1559" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNm1rQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--950270e10cb337007fdf37c5d4e5d673845bce0f/image.png" alt="image.png" />

However, if user starts using date-Picker on "Start of Operations", the error message shows correctly:
<img width="1381" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnVrQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7a56f8136dfff51e1ec82739ecf6e1c067a255b7/image.png" alt="image.png" />
<img width="1384" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjJrQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--852fd9c69f98cd7f5b2bab1e0f0f174cb4e0ee3b/image.png" alt="image.png" />

Switching "Start of Operations" back to 2024 and "End of Operations" back to 2024, it behaviors correctly.
<img width="1397" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNitrQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--631983df94b801290fdb206e71f12bc2b1002c51/image.png" alt="image.png" />

**Expected Behaviour**
The error message should only be shown when "End of Operations" year < "Start of Operations" year.

** Steps To Reproduce**
1. Add new FOM.
2. Pick first available Year from date-picker (the same as "Start of Operations" year).
3. Error message shows.

**Additional context**
* Backend does have same validation in place.

**Comment by gormless87** [comment]
@ianliuwk1019 - this seems OK, except that the first time I select an end date equal to the start date, the error message briefly flashes then disappears.

**Comment by ianliuwk1019** [comment]
Hi @gormless87 - thank you for verifying. Since main function is good, I will create a ticket for the minor initial date-pick slashing seen issue for this separately.
#559
