### ISSUE TITLE
Admin Summary Report's Comments Section Content Needs Padding.

### ISSUE THREAD

**Issue by ianliuwk1019** [bcgov/nr-fom#555]
**Describe the Bug**
This probably was overlooked after last major Angular upgrade due to records are not always visible.
The "Admin" frontend "Summary Report" Comment section seems to be missing padding so the content looks a bit strange.
<img width="1372" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkNvQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--49fa8e0223404f7ab7b9bd0525696ded9152f97f/image.png" alt="image.png" />

**Expected Behaviour**
Each category of the Comment section in Summary Report needs some reasonable padding for the content to look nicer.

** Steps To Reproduce**
Steps to reproduce the behaviour:
1. Go to FOM "Admin" frontend.
2. Search for a FOM which has public comment (or create one public comment if not present).
3. Go into Summary Report of the FOM.
4. Expend the Comment section with the category that has comments in there.

**Comment by OlgaLiber2** [comment]
@ianliuwk1019 I agree it looks strange. Can we put it in our FOM backlog and pull it into the sprint when we're doing other stylistic enhancements for FOM in the future? I would like to spend more time on FAM tickets that are more important to users in the next few sprints.

**Comment by ianliuwk1019** [comment]
I am pretty sure that the content for the Summary Report was good with padding long time ago.

I think due to the Angular upgrade, and probably nobody actually look into the look-and-feel on this page (since it needs content to be visible on display), this problem was not noticed.

The issue after investigation was because new version of Angular Material library for that particular component `<mat-card>` now needs `<mat-card-content>` if there is a content section, so it can render 'padding' by default.
This is fixed and in PR now.
@OlgaLiber2 @basilv

**Comment by gormless87** [comment]
Looks good
