### ISSUE TITLE
Deployment verification

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/nr-fom#56]
Longer term - after change freeze

Pipeline does some checks -readiness

Script tests for:
curl test against urls for different components

**Comment by DerekRoberts** [comment]
[7/7 10:36 AM] Vandegriend, Basil
For smoke testing (build verification): connect to API, connect to Public, connect to Admin

curl -X 'GET' \
  'https://fom-test.nrs.gov.bc.ca/api/district' \
  -H 'accept: application/json'
https://fom-test.nrs.gov.bc.ca/public/projects#splash

**Comment by DerekRoberts** [comment]
Maybe add curl commands here?
https://github.com/bcgov/nr-fom/blob/0caf59892274bf9b9cfe4d7c83a92da354694f9f/.github/workflows/pr-open.yml#L490

**Comment by ianliuwk1019** [comment]
@DerekRoberts , @basilv  For deployment verification (readiness checks)  in GHA workflow, if either of the checks fails, does it need to stop there before next job run?

Just paste a image log when verification ran successfully (at the bottom) but console prints out strange things in between (I didn't code for it to print them).
![image.png](https://images.zenhubusercontent.com/62a9ff93d8506f14758ef03a/ade971bf-c553-476c-8104-61e7da47fe7f)

**Comment by DerekRoberts** [comment]
@ianliuwk1019 Any failure is sufficient to stop the pipeline.  I like the -w http_code part in particular!  (BTW this has been moved into a Deployment Verification step for visibility.)

Good job!  :)

**Comment by ianliuwk1019** [comment]
In summary, after deployment is done for each environment for FOM in the pipeline, a workflow step is added next for testing the readiness of api/admin/public components.

- For api: issue request to test "${FOM_URL}/api/district".
- For admin: issue request to test "${FOM_URL}/admin/".
- For public: issue request to test "${FOM_URL}/public/".

Example for admin check for its **http response code**:
`
[ $(curl -L --max-redirs 5 -s -o /dev/null -w "%{http_code}" "${FOM_URL}/admin/") -ne 200 ]
`

Currently if either of the check (api/admin/frontned) fails, the pipeline will exit from shell `exit 1` for further step to run.
