### ISSUE TITLE
bug: reported no PROD-labeled images

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/nr-fom#561]
It was reported that there are no PROD-labeled images.  They are present, but hard to find due to the infrequence of PROD merge in this project/repository.  If this is a problem we can expand cleanup to reduce noise or deploy to PROD more regularly.

https://github.com/bcgov/nr-fom/pkgs/container/nr-fom%2Fadmin/164895394?tag=prod

https://github.com/bcgov/nr-fom/pkgs/container/nr-fom%2Fpublic/164895270?tag=prod

https://github.com/bcgov/nr-fom/pkgs/container/nr-fom%2Fapi/165330232?tag=prod

**Comment by MCatherine1994** [comment]
In the GitHub package registry for fom api images, we can't find any image with tag "prod", need to check the pipeline step "Promote images to PROD".
