### ISSUE TITLE
bug: API and cronjob using different images

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/nr-fom#562]
These should match.  Fix in [PR 564](https://github.com/bcgov/nr-fom/pull/564).

Update: 564 rolled into https://github.com/bcgov/nr-fom/pull/568.

**Comment by MCatherine1994** [comment]
The main deployment is using a "test" tag for the image and pass to the deployment pipeline. So when setup the image stream for api, it's pointing to the image with test tag. 

![Image](https://github.com/bcgov/nr-fom/assets/23131735/2f0a14d7-c415-4c9d-b7b6-0ffe1dc29c65)
![Image](https://github.com/bcgov/nr-fom/assets/23131735/fa299dc0-e1a5-4f45-a22f-5f2fbbc74d96)



The api image is using the one from image registry, but the cron job is getting from GitHub? Think they should use the same image. 
![Image](https://github.com/bcgov/nr-fom/assets/23131735/636b3918-96df-4bce-b7a1-4b22d05de004)

![Image](https://github.com/bcgov/nr-fom/assets/23131735/09193ff2-4e06-4f19-8374-5b51b97eb3b4)

**Comment by DerekRoberts** [comment]
Fixed manually, which is a terrible idea!  A proper solution is on the way.  Cronjob running tonight, so let's verify.

**Comment by DerekRoberts** [comment]
Proper solution in [PR 564](https://github.com/bcgov/nr-fom/pull/564).
