### ISSUE TITLE
feat: add image consistency

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/nr-fom#567]
API CronJob images are being pulled from GHCR, while the rest are imported into the OpenShift image registry first.  Find a way to make them all consistent, ideally using OpenShift.  That way we can keep an import of images for disaster-type deployments without GitHub.

Resolved in https://github.com/bcgov/nr-fom/pull/568.

**Comment by MCatherine1994** [comment]
Just add a question here,

So in the pr #564, we add "prod" tag to image every time after test deployment. And the plan in this ticket is to get both api and cronjob to pull the image directly from GHCR, with tag "prod".  Then the api and cronjob could end up use latest "prod" tag image, even we haven't do prod deployment? 

Maybe if pull from Openshift can solve the problem? Cause we only upload "prod" tag image to Openshift Prod image stream when doing prod deployment. 

Thanks!

**Comment by DerekRoberts** [comment]
@MCatherine1994 That's it and all safe!  We have an upcoming ticket for image registry consistency intended to make this significantly less nonsensical.  :P
