### ISSUE TITLE
Make existing FOM unit tests pass

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-fom#60]
Assess existing tests - do they make sense, are they adequate? Pick apart old test for value

Tests pass if run correctly; api unit tests pass
Improving coverage --separate ticket exists 
Communication/integration with p/l

AC:
each component has at least 1 test

Worthwhile tests to be incorporated into pipeline

**Comment by gormless87** [comment]
Existing tests fail and do not give adequate coverage

**Comment by DerekRoberts** [comment]
API unit tests work and are now consumed by the pipeline!  Coverage still very low.

E2E tests currently failing and will likely be removed later.

**Comment by DerekRoberts** [comment]
Only API unit tests were workable.  Now in the pipeline.  Other tests are out of scope and have their own tickets.
