### ISSUE TITLE
Update contact number on the public contact page

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-fom#601]
**Describe the task**
Update the phone on the public contact page
![Image](https://github.com/bcgov/nr-fom/assets/23131735/74a9d7f9-6dec-4354-a340-44aa3ee1b305)

**Acceptance Criteria**
- [x] Remove toll-free and outside numbers
- [x] Just display `250-952-6801 (Select option 1)` 
- [ ] third

**Additional context**
![Image](https://github.com/bcgov/nr-fom/assets/23131735/38b66edf-27d4-49b1-8182-22903ccd4cb7)

**Comment by gormless87** [comment]
Looks good, contact info update confirmed.
