### ISSUE TITLE
Revert status to "initial" for 3 FOMs

### ISSUE THREAD

**Issue by OlgaLiber2** [bcgov/nr-fom#609]
**Describe the task**
Revert status to "initial" for 3 FOMs: 

- 1282
- 1289
- 1290

**Acceptance Criteria**
- [x] completion of this task is communicated to Julius

**Additional context**
![Image](https://github.com/bcgov/nr-fom/assets/121979429/984d16cc-1ae6-40d2-b92c-32f2ee086357)

**Comment by MCatherine1994** [comment]
![Image](https://github.com/bcgov/nr-fom/assets/23131735/8838a0b6-fad3-43e2-a01b-fa908f36bc16)



![Image](https://github.com/bcgov/nr-fom/assets/23131735/f50d839d-31ce-4d2f-b8d4-d2bc7c33c0b7)



![Image](https://github.com/bcgov/nr-fom/assets/23131735/35a23618-f3c1-4813-93a8-9f115f0355a4)
