### ISSUE TITLE
Issue (PROD): FOM should use district email address to send email

### ISSUE THREAD

**Issue by ianliuwk1019** [bcgov/nr-fom#610]
**Describe the Bug**
For Cariboo Chilcotin Natural Resource District, the email was sent to "FLNR.AdminServicesCariboo@gov.bc.ca" at production FOM. It should be sent to district email with "DCC.Tenures@gov.bc.ca".

**Expected Behaviour**
Sent to "DCC.Tenures@gov.bc.ca" for Cariboo Chilcotin Natural Resource District.

**Actual Behaviour**
It was sent to "FLNR.AdminServicesCariboo@gov.bc.ca".

**Additional context**

**Comment by MCatherine1994** [comment]
![Image](https://github.com/bcgov/nr-fom/assets/23131735/9020cc3a-e058-472a-9af9-32c5dbf1b3a3)

**Comment by ianliuwk1019** [comment]
Based on prod data with the screenshot above, the district "Cariboo-Chilcotin" record does have correct "DCC.Tenures" email address with it.

Olga sent further clarification email to Julius. So we are waiting to see either this is real prod issue with more information on which FOM (finalized) was this email sent or if this was just for **TEST/Demo instance** (which was configured in oc template to send to "[FLNR.AdminServicesCariboo@gov.bc.ca](mailto:FLNR.AdminServicesCariboo@gov.bc.ca)).  

![Image](https://github.com/bcgov/nr-fom/assets/81595625/cc16209c-cf16-4821-9b0a-af0eb37f2c9a)
