### ISSUE TITLE
BCGW Replication: FOM_CUTBLOCKS_SP - API timeouts

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-fom#611]
**Describe the Bug**
There was an error during the replication to the BCGW for FOM_CUTBLOCKS_SP: 'HTTP/1.1 504 Gateway Time-out'. So they call our api directly to connect with the BCGW, and that api returns a time out error. Investigate either increase the time out time, or increase the capacity.

**Acceptance Criteria**

- [x] Update the default timeout of Openshift Route config in the openshift config file `api/openshift.deploy.yml`, set it to 120s
![Image](https://github.com/bcgov/nr-fom/assets/23131735/ec694dd4-d819-4bdc-a28f-0439c4ccf870)
- [x] Add a info log to print out when the process is finished 

![Image](https://github.com/bcgov/nr-fom/assets/23131735/f3346b07-317a-4baa-84d4-c86b172ae6dc)

**Additional context**
Found out the issue was caused by the Openshift default route timeout is 30s, somehow our PROD takes longer time to query compare with TEST, there will be a new ticket (#612)  to investigate more. Basil did a quick fix through Openshift yaml, and we need this ticket to make the change in the Openshift config file. 

![Image](https://github.com/bcgov/nr-fom/assets/23131735/962084c6-1a6f-479b-85e4-fa4ef2576820)

**Comment by MCatherine1994** [comment]
![Image](https://github.com/bcgov/nr-fom/assets/23131735/eb227f1d-b85b-4a62-afe2-7af578821d8d)

**Comment by ianliuwk1019** [comment]
Interestingly, when looking into deployed (DEV) pod for performance of the "/bcgw-extract" execution, it returns fast in 3ms.
(`curl https://fom-13.apps.silver.devops.gov.bc.ca/api/spatial-feature/bcgw-extract?version=1.0-final -H "Accept: application/json"`)
@basilv 
```
{"level":"info","time": 2024-04-04T20:59:53.534Z,"pid":1,"hostname":"fom-13-api-1-dzbmw","req":{"id":3,"method":"GET","url":"/api/spatial-feature/bcgw-extract?version=1.0-final","query":{"version":"1.0-final"},"params":{"0":"spatial-feature/bcgw-extract"},"headers":{"user-agent":"curl/7.68.0","accept":"application/json","host":"fom-13.apps.silver.devops.gov.bc.ca","x-forwarded-host":"fom-13.apps.silver.devops.gov.bc.ca","x-forwarded-port":"443","x-forwarded-proto":"https","forwarded":"for=165.225.210.217;host=fom-13.apps.silver.devops.gov.bc.ca;proto=https","x-forwarded-for":"165.225.210.217"},"remoteAddress":"::ffff:10.97.28.1","remotePort":32762},"msg":"Start get /spatial-feature/bcgw-extract"}
{"level":"info","time": 2024-04-04T20:59:53.537Z,"pid":1,"hostname":"fom-13-api-1-dzbmw","req":{"id":3,"method":"GET","url":"/api/spatial-feature/bcgw-extract?version=1.0-final","query":{"version":"1.0-final"},"params":{"0":"spatial-feature/bcgw-extract"},"headers":{"user-agent":"curl/7.68.0","accept":"application/json","host":"fom-13.apps.silver.devops.gov.bc.ca","x-forwarded-host":"fom-13.apps.silver.devops.gov.bc.ca","x-forwarded-port":"443","x-forwarded-proto":"https","forwarded":"for=165.225.210.217;host=fom-13.apps.silver.devops.gov.bc.ca;proto=https","x-forwarded-for":"165.225.210.217"},"remoteAddress":"::ffff:10.97.28.1","remotePort":32762},"msg":"End get /spatial-feature/bcgw-extract for 3.1206917762756348ms."}
```

**Comment by basilv** [comment]
Hmm, that's unexpectedly fast. Is there all the test data (should be).

**Comment by ianliuwk1019** [comment]
This is the spatial view for dev db:

![Image](https://github.com/bcgov/nr-fom/assets/81595625/45a7d3d0-f829-44b5-a58e-98323886c0ef)

**Comment by ianliuwk1019** [comment]
Fixed the missing "await" for function in PR#614.
Now the bcgw function performance is correct:
(Dev - for 18167 spatial feature rows)
![Image](https://github.com/bcgov/nr-fom/assets/81595625/2d9907b1-3f76-4b24-b3d0-6788a9bd1a24)

**Comment by ianliuwk1019** [comment]
Verified in Test environment:
![Image](https://github.com/bcgov/nr-fom/assets/81595625/15cd74cf-3298-4bc3-9762-8f9939975fbe)
Takes: 14094.4197473526ms.

```
{"level":"info","time": 2024-04-05T17:08:28.244Z,"pid":1,"hostname":"fom-test-api-457-5298c","req":{"id":1,"method":"GET","url":"/api/spatial-feature/bcgw-extract?version=1.0-final","query":{"version":"1.0-final"},"params":{"0":"spatial-feature/bcgw-extract"},"headers":{"user-agent":"curl/7.68.0","accept":"application/json","host":"fom-test.nrs.gov.bc.ca","x-forwarded-host":"fom-test.nrs.gov.bc.ca","x-forwarded-port":"443","x-forwarded-proto":"https","forwarded":"for=165.225.210.217;host=fom-test.nrs.gov.bc.ca;proto=https","x-forwarded-for":"165.225.210.217"},"remoteAddress":"::ffff:10.97.28.1","remotePort":20966},"msg":"Start get /spatial-feature/bcgw-extract"}
{"level":"info","time": 2024-04-05T17:08:42.338Z,"pid":1,"hostname":"fom-test-api-457-5298c","req":{"id":1,"method":"GET","url":"/api/spatial-feature/bcgw-extract?version=1.0-final","query":{"version":"1.0-final"},"params":{"0":"spatial-feature/bcgw-extract"},"headers":{"user-agent":"curl/7.68.0","accept":"application/json","host":"fom-test.nrs.gov.bc.ca","x-forwarded-host":"fom-test.nrs.gov.bc.ca","x-forwarded-port":"443","x-forwarded-proto":"https","forwarded":"for=165.225.210.217;host=fom-test.nrs.gov.bc.ca;proto=https","x-forwarded-for":"165.225.210.217"},"remoteAddress":"::ffff:10.97.28.1","remotePort":20966},"msg":"End get /spatial-feature/bcgw-extract for 14094.4197473526ms."}
```

**Comment by ianliuwk1019** [comment]
Released to production.
