### ISSUE TITLE
Add BCiMaps button to public interface

### ISSUE THREAD

**Issue by OlgaLiber2** [bcgov/nr-fom#619]
**Describe the task**
Add BCiMaps button to FOM's public interface

**Acceptance Criteria**
- [x] update the text on the about page for the iMpasBC button (see screenshot below)
`View and analyze hundreds of map data layers compiled from across the B.C. Government, and other public sector agencies. This includes the FOM layers, which can be overlayed onto other layers, allowing the user to see FOM features from all published FOMs on one comprehensive map.`
- [x] add button that launches iMapsBC in a new tab (https://maps.gov.bc.ca/ess/hm/imap4m/)

**Additional context**

![Image](https://github.com/bcgov/nr-fom/assets/121979429/69225b44-368e-484f-8961-df9a9d65e312)

![Image](https://github.com/bcgov/nr-fom/assets/23131735/6cc5abf8-9bd2-4b0c-891f-eb5734ec97c9)

**Comment by ianliuwk1019** [comment]
Hi @OlgaLiber2 , I guess in discussion we favor to use icon for the iMapsBC link.
Do you have choice on the icon to use?
In FOM project, it seems that it is using two different sources (some free) for the icons:
- Bootstrap icons: https://icons.getbootstrap.com/
- Font Awesome icons: https://fontawesome.com/icons

**Comment by OlgaLiber2** [comment]
@ianliuwk1019 that's the universal icon for opening in a new tab

![Image](https://github.com/bcgov/nr-fom/assets/121979429/f5dfb622-6476-461d-ba10-a3e29a204713)

**Comment by ianliuwk1019** [comment]
Hi @OlgaLiber2 , I can only find this **free version** icon from FontAwesome (the paid pro version has better looking); the Bootstrap has similar one but does not look better than FontAwesome icon.
I did not enclose the text with border, as to be more like a link to open than a button (just my preference).
Also it uses the same text from "About" page.
Do you feel it is ok, or do you like to make it as above?
![Image](https://github.com/bcgov/nr-fom/assets/81595625/9138e39b-3c1f-4c07-84c9-640fc50f52b5)

**Comment by OlgaLiber2** [comment]
@ianliuwk1019  I think it needs to be a ghost button and the wording that we have in the mockup.

**Comment by ianliuwk1019** [comment]
Available at TEST environment: https://fom-test.nrs.gov.bc.ca/public

**Comment by OlgaLiber2** [comment]
@ianliuwk1019 looks good. Please deploy to prod. @MCatherine1994

**Comment by ianliuwk1019** [comment]
This is now available at prod: https://fom.nrs.gov.bc.ca/public/projects.
