### ISSUE TITLE
Enforce BCeID Business Login in FOM

### ISSUE THREAD

**Issue by ConradBoydElliottGustafson** [bcgov/nr-fom#62]
It looks like FOM allows logins through BCeID BASIC, as well as IDIR. Not sure if this is true or why it was done that way. Check it out and make sure?

It could be that the path of least resistance on the Keycloak realm was to use the IDP that was already set up to allow BCeID basic & business. Again, not sure. FOM should be checking that the IDP used to log in was BCeID business, otherwise it is totally possible to log into FOM using basic or IDIR. 

Not sure the business requirements at this time, just leaving this ticket here to make sure we don't forget about it.

**Comment by basilv** [comment]
FOM requires both BCeID and IDIR logins. IDIR are generally 'ministry users', and BCeID are 'industry users' in terms of access but there will be exceptions. I know we had some discussions about basic vs business BCeID, but I don't really remember anymore if there was actually a requirement to allow basic BCeID.

**Comment by gormless87** [comment]
Will enforce this in FAM rather than doing this work in FOM.

Closing,
