### ISSUE TITLE
Clarification on commenting close date

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-fom#628]
**Describe the task**
Our user is confused about the commenting close date, cause they were trying to submit comment on the commenting close date, but it's not allowed anymore. 

**Acceptance Criteria**
~~- [ ] Shift the current commenting closing date to one day before~~ 
~~- [ ] Specify the time when they select the commenting closing date, like the commenting closing date will be on May 15th, 11:59pm~~ 
- [x] Still stay with 'plus 30 days' logic
~~- [ ] Update the cron job for workflow state change when change the state to "commenting closed"~~
~~- [ ] historical data adjusted (verify with business area)~~
- [ ] See Olga's [comment](https://github.com/bcgov/nr-fom/issues/628#issuecomment-2142934249) below, only public side frontend changes. 

**Additional context**
- ![Image](https://github.com/bcgov/nr-fom/assets/23131735/d78cb502-1175-47ec-9486-206f96892920)

- From the code logic, we run work flow state change cron job at 8am (UTC) every day, and it will `Query for projects with workflowState = COMMENT_OPEN and 'COMMENT_CLOSED_DATE' equal to or before today:  update to have workflow state = COMMENT_CLOSED`, so the real deadline will be around 1am PST on the commenting close date

**Comment by MCatherine1994** [comment]
Currently the update workflow state cron job run at 1am PST (which is 8am UTC), which means if the commenting close date set to be May 15, the actual deadline is 1am BC time on May 15. So we can say we accept submissions before May 15th, or maybe until May 14th?

**Comment by ianliuwk1019** [comment]
Not sure if the "**30**" days rule is a hard rule, changing it probably would not comply with legislation.
If that's true, maybe the `**Public**` did not understand or maybe FOM needs to indicate this rule at frontend clearly to the `**Public**`.

Many places, frontend/backend/process rely on this rule.
A simple admin site inputs for "Commenting Open Date" and "Commenting Close Date" can illustrate this.
![Image](https://github.com/bcgov/nr-fom/assets/81595625/e3cae94b-3c33-45ae-98a3-34d01ee0edca)

If Commenting Open Date is 2024-05-17 (**inclusive**), then plus **30** days is 2024-06-15 (**inclusive**), so the earliest Commenting Close Date is on 2024-06-16 (**exclusive**) and if I understand correctly, "Close" imply on this date the FOM is "CLOSED". 

If we would need to make the scheduled process (state-change to close the FOM) runs precisely on the BC time 0:00am, NestJS cron scheduling might be of help:
![Image](https://github.com/bcgov/nr-fom/assets/81595625/0a53df8a-e840-426d-88bb-9d7da5004c04)
Basil mentioned this requires bigger change and testing.
@OlgaLiber2 @basilv

**Comment by ianliuwk1019** [comment]
Pending for Olga to evaluate (with client possibly):

Option 1: (Resolving public/submitter confusion for reasonable easy changes) 
> Public: FOM Detail confusing wording change on:
![Image](https://github.com/bcgov/nr-fom/assets/81595625/801bf27a-ea07-4631-88ee-262d6c432eef)
> Admin: New FOM entering "Commenting Closed Date":
![Image](https://github.com/bcgov/nr-fom/assets/81595625/22305611-9327-4263-b72c-4ebb760f6547)


Option 2: (Will need big efforts on all modules tweaking)
- Context switching from "Commenting Closed Date" to "Commenting Closing Date".
- Propagates semantics switching deeper: all involved logic to have "1 day shifted".
- Impact: Public code, Admin code, all related backend logic, text/labeling/error, tests, scheduled process (probably not),  db column rename(?), data fix (1 day shift), training module, and else?

**Comment by MCatherine1994** [comment]
Confirmed with Julius, we can update the wording on Public site for now

**Comment by OlgaLiber2** [comment]
We had a meeting with Julius yesterday and we agreed to keep the admin portal as is and make the changes to wording on the public facing side. We might need to add a calculation to show on the public side a day one day before it is selected on the admin portal. 

I also have a few minor styling changes proposed for the "FOM details" section to make it more scannable and have better content hierarchy. I am hoping to meet with Julius tomorrow to discuss the changes and get his approval. If he approves, I'm hoping it can be part of this ticket since it's not a lot of work. @ianliuwk1019 

Proposed styling changes: 


![Image](https://github.com/bcgov/nr-fom/assets/121979429/aa1579e0-fc30-43c7-8ed3-67a85960d216)

**Comment by OlgaLiber2** [comment]
@ianliuwk1019 Julius is good with the change. You can go ahead and implement the date change on the public page. 

Julius will also provide me with content (hopefully next week) for the hover icon to explain "validity period". 

here is a screenshot with the updated mockup :) 

(link to mural board if you need it https://app.mural.co/t/climatechange4363/m/climatechange4363/1716833075792/bf88d19142c7c0bfca6670d2315d1f9ed9c9467e?sender=u84301558fa490f89e6792901)

![Image](https://github.com/bcgov/nr-fom/assets/121979429/fab0100c-1af9-412b-a037-ceb7403af0a6)

**Comment by ianliuwk1019** [comment]
Hi @OlgaLiber2 ,
Now I remembered what I was wondering in mockup.
The "**Periods of operations**" is new, it isn't in current production. But no worry, I will add this in.
Just want to let you know the "**Periods of operations**" is different than the "**valid until**" (in code, it is "validityEndDate"). The two have different legal meaning I think (but Julius can give you details).
For "**validityEndDate**", it is:
* Non-BCTS FOM: Commenting **Open** Date + 3 years.
* BCTS FOM: Commenting "**Closed**" Date + 3 years. (not closing date)


So when putting both of them side by side, I wonder that may give public some confusion (I am confused if I don't look at the code); but I will put them same as your mockup.

**Comment by basilv** [comment]
@ianliuwk1019 I think the mockups look fine, I don't see the issue with "Period of Operations" being combined. (I should have thought of that :)

**Comment by ianliuwk1019** [comment]
> [@ianliuwk1019](https://github.com/ianliuwk1019) I think the mockups look fine, I don't see the issue with "Period of Operations" being combined. (I should have thought of that :)

Thanks Basil!!

**Comment by OlgaLiber2** [comment]
@ianliuwk1019 I agree about that writeup about validity date is confusing because it has the two different criteria for BCTS and non-BCTS submissions. I mentioned it to Julius, he's looking at the wording. My question to him was if we can display the writeups that relates to BCTS criteria only BCTS FOMs and the writeup on non-BCTS FOMs when they submitter is industry... according to him both criteria has to be listed in the writeup.. But I'm hoping to give it another iteration at some point to make it more clear. I agree with you it's confusing.

**Comment by OlgaLiber2** [comment]
@ianliuwk1019 try darker gray for this text, it's hard to read and more spacing. Here is the styling I updated (circled in red): 


![Image](https://github.com/bcgov/nr-fom/assets/121979429/1b38e201-914a-47a1-af8f-7f4a607c6dff)



For FOMs with closed commenting period let's take out the "commenting opened on..." line so it looks like this: 

![Image](https://github.com/bcgov/nr-fom/assets/121979429/88ae37a4-ed67-44f5-9652-0f9597f4247c)

**Comment by ianliuwk1019** [comment]
> [@ianliuwk1019](https://github.com/ianliuwk1019) try darker gray for this text, it's hard to read and more spacing. Here is the styling I updated (circled in red):
> 
> ![Image](https://private-user-images.githubusercontent.com/121979429/336625449-1b38e201-914a-47a1-af8f-7f4a607c6dff.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1NDMzNjMsIm5iZiI6MTcxNzU0MzA2MywicGF0aCI6Ii8xMjE5Nzk0MjkvMzM2NjI1NDQ5LTFiMzhlMjAxLTkxNGEtNDdhMS1hZjhmLTdmNGE2MDdjNmRmZi5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNFQyMzE3NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNmJjZDc3ZmEzZDcyNDc1OWE5ODNiMzQxMDg3ZGM3ZjJkMGZiMDI4YThhMzhkNzVhZTI5YzJiM2JiZTViNWI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gQAd1fcAY4wKQvF6ykJy6ltzr4Bh0jgYXnbd-_0vo8o)
> 
> For FOMs with closed commenting period let's take out the "commenting opened on..." line so it looks like this:
> 
> ![Image](https://private-user-images.githubusercontent.com/121979429/336629407-88ae37a4-ed67-44f5-9652-0f9597f4247c.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1NDMzNjMsIm5iZiI6MTcxNzU0MzA2MywicGF0aCI6Ii8xMjE5Nzk0MjkvMzM2NjI5NDA3LTg4YWUzN2E0LWVkNjctNDRmNS05NjUyLTBmOTU5N2Y0MjQ3Yy5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNFQyMzE3NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYzQ0YjVhOTA0OTI1ZTFhYzk0NmUwMzUwYmNiMzNkNmJhOWI1ZGZkYWRlNjM1YWJjMDlhMDcyMzg0YzJhMjA4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HDIsV9C_JMTVJVmqJjyGw5kuDOvhC_hBhFxbYbAyLuU)

Thank you @OlgaLiber2 !! Suggested changes are done and deployed.
