### ISSUE TITLE
BCGW failure caused by wrong plannedDevelopmentDate

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-fom#629]
**Describe the task**
BCGW extract api failed because of a wrong date in one of the cut block

**Acceptance Criteria**
- [x] Get approval from business and do the data fix

**Additional context**
- Will need to add in appropriate validation (valid date, string length etc.), could create another ticket for it #631
- 
![Image](https://github.com/bcgov/nr-fom/assets/23131735/ce18cf2f-d12a-4085-816f-f26493fbb7b3)

- 
```
select planned_development_date, name, cut_block_id, submission_id from cut_block where submission_id in (select submission_id from submission where project_id=1318);
```
![Image](https://github.com/bcgov/nr-fom/assets/23131735/f46b1187-ca3d-4a9d-bbcb-644b455d1ef2)

**Comment by MCatherine1994** [comment]
Olga confirmed with Sean, they are fine with the data fix. Fixed as below:

![Image](https://github.com/bcgov/nr-fom/assets/23131735/19d97596-2c6c-4c00-86f9-72ccfa67372b)

**Comment by MCatherine1994** [comment]
@OlgaLiber2 just wondering if we want to paste the email for Sean's approval in this ticket as well? thanks!

**Comment by OlgaLiber2** [comment]
change confirmed with Sean @MCatherine1994 

![Image](https://github.com/bcgov/nr-fom/assets/121979429/eaa663d5-ed35-48fd-96ab-6f9aa5769773)
