### ISSUE TITLE
Update how-to video and add the training button on FOM public

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-fom#634]
**Describe the task**
Update the how-to video link on FOM public site, "About" page and the popup they open FOM website. Add a new button on the top navigation bar, same as the admin site, link to the how-to video as well.

**Acceptance Criteria**
- [x] Update the how-to video link on FOM public About page
- [x] Update the how-to video link on FOM public popup
- [x] Add a training button on top navigation, and link to the how-to video

**Additional context**
- New how to video link: [Introducing the new Forest Operations Map (FOM) Online Portal (bcgov.github.io)](https://bcgov.github.io/forestry-digital-services/assets/training/FOMpublic/index.html#/lessons/bPu8Fx187gWLV3rC5RjpbKEKkDBwIX93)

![Image](https://github.com/bcgov/nr-fom/assets/121979429/54b44f1c-3dca-4248-904c-4fcc7163b802)

**Comment by MCatherine1994** [comment]
Hi Olga @OlgaLiber2, do we want to open the how-to videos in a new tab, or in the current tab?

**Comment by OlgaLiber2** [comment]
@MCatherine1994 new tab with the icon indicating it'll open in a new window (like this one https://thenounproject.com/icon/new-window-299638/)

**Comment by MCatherine1994** [comment]
Thanks @OlgaLiber2 , do you mind have a quick review on it? https://fom-44.apps.silver.devops.gov.bc.ca/public



![Image](https://github.com/bcgov/nr-fom/assets/23131735/a83e511c-f017-4b54-9401-c1d0a06e3f75)



![Image](https://github.com/bcgov/nr-fom/assets/23131735/6ff33a83-29e1-41d6-9d35-24cfe83c4291)



![Image](https://github.com/bcgov/nr-fom/assets/23131735/c944b81a-07f6-463f-9f1c-5844a75083cf)
