### ISSUE TITLE
Updates to an existing PR should result in deploy of a new image

### ISSUE THREAD

**Issue by basilv** [bcgov/nr-fom#64]
If an existing PR is updated, it appears that new images are built but not deployed.
Updating existing PRs is very common due to code reviews, if nothing else, and it is confusing to forget that a change has not automatically been deployed.

Workaround is to close the PR and reopen it, as this will trigger cleanup of the dev resources associated with the PR, and then recreate them, which guarantees that the latest image is used in the deployment.

**Comment by DerekRoberts** [comment]
This is important.  Moving to current sprint.
