### ISSUE TITLE
BCGW api error

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-fom#649]
**Describe the task**
Got a service desk ticket from Corinne that the BCGW failed again last night and this morning
https://dpdd.atlassian.net/servicedesk/customer/portal/1/DATABC-3873
. It's a 502 Bad Gateway error. Checked the Openshift logs, think it's the out of resource issue again, might need to adjust the openshift requested memory/cpu again

![Image](https://github.com/bcgov/nr-forests-access-management/assets/23131735/d1984c21-f2e7-4316-990d-c48282ce978a)

**Acceptance Criteria**
- [x] Investigate the problem
- [x] Adjust limit memory to 4G in the pipeline

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by ianliuwk1019** [comment]
The mu is the node's "memory usage" term internally: `const mu = process.memoryUsage();`

**Comment by MCatherine1994** [comment]
fyi

![Image](https://github.com/bcgov/nr-fom/assets/23131735/1bc53ff4-13a1-4cac-97dd-46fa6433c6b1)

**Comment by MCatherine1994** [comment]
Discussed with Basil and Ian, the memory usage of the BCGW api can be 1.4G, which is still under the memory limit 2G. We found that could cause by the run time memory limit by Node. Run the following command to both TEST and PROD fom-api pod container `console.log(`node heap limit = ${require('v8').getHeapStatistics().heap_size_limit / (1024 * 1024)} Mb`)`. The run time memory limit for Node is based on the limit of the container. By observing, it sets the limit to half of the container limit. 
![Image](https://github.com/bcgov/nr-fom/assets/23131735/d6a61c66-360a-4151-b930-b333fa59954e)

So to hotfix it for now without merging the geometry simplification, we manually update the memory limit to 4G, so the Node run time memory limit will be 2G. Pods automatically restarts after the change. 

![Image](https://github.com/bcgov/nr-fom/assets/23131735/ec079720-e7d1-4a11-b648-79f6c9c20d40)

 

Test the api `curl -X 'GET' 'https://fom.nrs.gov.bc.ca/api/spatial-feature/bcgw-extract?version=1.0-final' -H 'accept: application/json'`, and check the logs, seems work fine now. 
![Image](https://github.com/bcgov/nr-fom/assets/23131735/7a4fb479-e4d2-47d0-8191-c304bb41b42b)

**Comment by ianliuwk1019** [comment]
Thanks Catherine! I took your information and added to our wiki troubleshooting.

**Comment by MCatherine1994** [comment]
Verified on Jun 28, the api call from last night was successful
![Image](https://github.com/bcgov/nr-fom/assets/23131735/bb1fcf46-f70f-4305-8eaa-cbc37d912766)


![Image](https://github.com/bcgov/nr-fom/assets/23131735/381c52fc-11e8-41f4-ab95-15642d77d52a)
