### ISSUE TITLE
Update FOM 1282 status

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-fom#655]
**Describe the task**
As required by Sean, update the FOM 1282 status back to commenting closed. 

![Image](https://github.com/bcgov/nr-fom/assets/23131735/35a7823a-88b2-496d-ad4d-ce7e4af9f250)

**Acceptance Criteria**
- [x] Update the status of FOM 1282 to `COMMENT_CLOSED `

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by ianliuwk1019** [comment]
When FOM is finalized the email is sent to the district.
If we switch back to Commenting Closed status and finalized again, probably Sean will need to inform the district for this FOM is not ready for district (from previous email sent)

**Comment by MCatherine1994** [comment]
![Image](https://github.com/bcgov/nr-fom/assets/23131735/9c775955-3576-452c-9c44-157d355738be)


![Image](https://github.com/bcgov/nr-fom/assets/23131735/ba7a9671-2004-4df7-b8ee-e0e55d9f08f8)




![Image](https://github.com/bcgov/nr-fom/assets/23131735/6ca24a62-fda0-4da7-9433-1ddb2c6ae24d)
