### ISSUE TITLE
Review and address security vulnerbilities

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-fom#660]
**Describe the task**
Review the security vulnerabilities and solve the high ones. 

**Acceptance Criteria**
- [x] Work on the fixing for high security vulnerabilities
- [x] Triage issues that need extra scrutiny or work

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by ianliuwk1019** [comment]
What's being taken care of this time:
- Remove unnecessary 'reflect-metadata', upgrade packages 'supertest', '@typescript-eslint/eslint-plugin'.
- Update NestJS package to ^10.0.0 and verified.
- Run npm install to update dependencies, this will eliminate some existing security vulnerabilities.
- Fix minor admin summary page console error.
- Use nodejs 20 and caddy 2.8.4 for FOM docker build images. (previously was run on nodejs 18, and will not be supported 2025)
- Clean up and close some irreverent issues from dependabot/code sanning. 

After the clean up and upgrade, issues reduced from >30 to 3:
![Image](https://github.com/user-attachments/assets/5052df79-8133-4190-a936-5216f1002274)

The remaining high security vulnerabilities are currently having no patch to upgrade them (we don't direct use them, it's in package-lock.json). We can wait for sometime for next round to have a look:
![Image](https://github.com/user-attachments/assets/736d269b-5e8e-4c09-a636-469360cf9f48)

One high vulnerabilities in code scanning is already tracked by ticket #374, can be scheduled (not urgent) to fix it next time for FOM planning.
![Image](https://github.com/user-attachments/assets/70bf1fc3-ba10-407d-bbde-08178d76c9ad)
@OlgaLiber2
