### ISSUE TITLE
Fix Admin Search By FOM Number

### ISSUE THREAD

**Issue by ianliuwk1019** [bcgov/nr-fom#663]
**Describe the Bug**
The previous implementation (#438) for admin side search by FOM Number implementation was working locally that it can filter on particular existing FOM number, however, very strange the TEST deployment does not work when enter existing FOM. It does not filter the record.

**Actual Behaviour** **Screenshots**
TEST environment FOM Number search does not work.
![image](https://github.com/user-attachments/assets/a05f8f99-1a74-404a-aa57-10f57ccd59b5)

The param is present in network tab correctly, no error at backend. Not sure if error has something to do with this (content-security-policy):
![image](https://github.com/user-attachments/assets/277cae6d-1175-4e33-a72a-45a0b2d6bdba)

**Desktop (please complete the following information):**
 - TEST environment

**Additional context**
- Original code works locally (can filter on particular FOM number, result = 1), but TEST environment does not work.

**Comment by ianliuwk1019** [comment]
It seems the problem is because on TEST deployment the swagger did not show there is a new "projectId" param for "find" endpoint:

![Image](https://github.com/user-attachments/assets/9207e97e-5a6d-4705-af5d-eef36fff3625)

**Comment by ianliuwk1019** [comment]
Tried rolling out (Openshift) api deployment again, does not work. Still not filtering FOM by projectId.
Looking into image, curious why I can't find the image from the sha identifier:
![Image](https://github.com/user-attachments/assets/624df63c-f6ed-41af-8bea-15aea64fbcfc)

**Comment by ianliuwk1019** [comment]
Hi @MCatherine1994, I looked again at github api package (image), I can find the 'sha' hash ("`7b3f042830dab1602495b439494245ba3c6227e2113ab088ea575acc05191e0e`") from the imageStream at .... **untagged version, page 2, 26 days ago**... why is OpenShift imageStream for TEST (`fom-test-api`) today's deployment is referencing to a untagged one 26 days ago? It really does not make sense to me!!
![Image](https://github.com/user-attachments/assets/6958aebb-619a-4c45-99a3-dd89203a57ee)
![Image](https://github.com/user-attachments/assets/8464f79e-ab39-4215-9f02-84129b3a6762)
@basilv do you have idea?

I will merge the dummy PR and see what happens.

**Comment by basilv** [comment]
That does seem weird, I don't have any idea just looking at the above. Have you asked Derek?

**Comment by ianliuwk1019** [comment]
The problem seem to be resolved itself by creating another dummy PR (dummy touched on api module to promote merge-to-main pipeline).

![Image](https://github.com/user-attachments/assets/f531d984-eb60-40ce-a190-6622a9c5b5f9)

I can now on TEST search by FOM Number and get back filtered 1 result.
![Image](https://github.com/user-attachments/assets/bcab8552-2dc7-4329-8027-9e9ac4fa2c27)

The gihub image tagging:
![Image](https://github.com/user-attachments/assets/3897d83e-2253-4bc3-915e-3c7da043982a)

The OpenShift (TEST) imageStream got a new hash after new PR 15 merge to main (for TEST deployment)
![Image](https://github.com/user-attachments/assets/0bb20681-928b-4a7a-8fe5-ea52d8c5af19)

**The remaining strange thing** is although now api works, the imageStream **hash does not match** with the one tagged with "**test**" at github (but the one from 17 hours ago, which is still having the working code at original PR11 for Search By FOM Number).
`sha256:5e833d8b75a907bade0831484d057d7be87b68341343910fc28ceda3400cb08e`
![Image](https://github.com/user-attachments/assets/fbe926f1-7480-4fa6-b0f4-f93c0a7632fe)
Does not match on github one:
![Image](https://github.com/user-attachments/assets/73418a9b-736d-4565-b021-e84040f1870f)
(Openshift imageStream hash) Can be found from untagged version:
![Image](https://github.com/user-attachments/assets/3b83db10-8d1d-4bb3-843a-746d76365bbd)
