### ISSUE TITLE
Remove unnecessary dependencies from package.json in API, Public, Admin

### ISSUE THREAD

**Issue by basilv** [bcgov/nr-fom#68]
After the components are split, remove unnecessary package.json dependencies. E.g. API back-end shouldn't depend on Angular (while front-end will). E.g. remove nx.

**Comment by gormless87** [comment]
This is being actioned through the 'separate' issues

**Comment by basilv** [comment]
I know I missed the last week, but are we sure this was done as part of the separation?

**Comment by gormless87** [comment]
I recall some 'check with Basil' uncertainty around this

**Comment by DerekRoberts** [comment]
@basilv @gormless87 I believe @ianliuwk1019 did this.  Another pass or doublecheck can't hurt.

**Comment by basilv** [comment]
Agreed, and I know the option exists to remove some dependencies that requires cleaning up (refactoring) some existing code, so I've reopened this to reflect the additional work that still can be done. (As to my motivation to reduce dependencies, see the dependabot alerts issue, easiest way to deal with those is to get rid of the dependency :)

**Comment by basilv** [comment]
@ianliuwk1019 popper.js dependency in public component is referenced by angular.json, but otherwise doesn't seem to be used. Any concerns with removing it from public.

(I am working on removing various unused dependencies, including removing popper.js from api and admin components.

**Comment by ianliuwk1019** [comment]
@basilv I might have missed removing popper.js, thanks. No concerns, if you still can build after removing it; I kind of recall error for build without popper.js at frontend in the past.
