### ISSUE TITLE
New FOM API for FSP TS

### ISSUE THREAD

**Issue by OlgaLiber2** [bcgov/nr-fom#686]
**Describe the task**
New API.
The API will be public accessible and allow to search for FOM related to (by) FSP ID. Apply naming convention to designate this API as used by external parties.

**Acceptance Criteria**
- [x] New API is built with search params available (FSP ID)
- [x] Add Auth guard if needed.
- [x] Add/Create/Adjust tests as needed.

**Additional context**
- Design discussion around what the API returns: existing `ProjectPublicSummaryResponse` as result, or with new response object for limited information.

[FSP TS FOM API Request.pdf](https://github.com/user-attachments/files/16732139/FSP.TS.FOM.API.Request.pdf)

![Image](https://github.com/user-attachments/assets/f9432bd4-93a9-467e-aca4-652bc949fd6c)

**Comment by ianliuwk1019** [comment]
Hi @basilv , just to confirm with you to see if the endpoint "path" and return json fit your expectation (haven't finished coding yet).
![Image](https://github.com/user-attachments/assets/4296c063-2ba3-4326-86fd-0fb40780c576)

This is to add endpoint into current `project.controller.ts`.
Although I am thinking to separate it out of "project" into something like `GET /api/fsp-tracker` without "/project", that will need another controller class (which I feel is fine but a bit more work).

**Comment by basilv** [comment]
Yes, I want it completely separate to make it clear it is used by external... I haven't decided on a good name (feel free to suggest), but definitely a separate controller class.

**Comment by ianliuwk1019** [comment]
Verified on TEST environment, it is good.
![Image](https://github.com/user-attachments/assets/71c61586-62db-4aaf-ad08-6e81668a9ee0)

The Swagger link is: https://fom-test.nrs.gov.bc.ca/api#/external/ProjectsByFspController_findByFsp
Please remind the FSP Tracker team, this is no official production link and do not code it into their either test or production environment. Thanks. Only for them to verify if it fit requirement.
@OlgaLiber2

**Comment by OlgaLiber2** [comment]
I sent an email to Viktor Novoselov to ensure the API meets their requirements. Anticipating to hear back from Viktor on Monday.

**Comment by ianliuwk1019** [comment]
Confirmed from FSP TS the api fit the requirement. Close this ticket.
![Image](https://github.com/user-attachments/assets/be6c8b4f-99ff-42cf-a85a-c8f5e76e9d2e)
