### ISSUE TITLE
Disable FOM form modifications/updates when commenting period is open

### ISSUE THREAD

**Issue by OlgaLiber2** [bcgov/nr-fom#692]
**Describe the task**
Email from Julius: 
![Image](https://github.com/user-attachments/assets/12024444-16cb-40d3-a9e1-91efe95af5e5)

![Image](https://github.com/user-attachments/assets/b6b6c321-f00d-4389-afb0-a764b0d835d8)
![Image](https://github.com/user-attachments/assets/f8caaad5-b002-419f-a5c3-9e79c52fa2d2)

**Acceptance Criteria**
- [ ] first
- [ ] second
- [ ] third

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by ianliuwk1019** [comment]
@basilv 
I have created a urgent PR [#693](https://github.com/bcgov/nr-fom/pull/693) just for frontend.
We will need to revisit backend to change/add/remove validation during "update".
@craigyu

**Comment by ianliuwk1019** [comment]
Clarification from Julius:
![Image](https://github.com/user-attachments/assets/4c2064b3-1e11-45ad-936f-53599943438b)


**Commenting Open Status**:
```
1. Do not make any changes to the Commenting Open Date and Commenting Closed dates. Submitters should still be abled to lengthen/extend the commenting period, and reviewers should still be able to shorten or lengthen the commenting period
 
2. The following fields should be locked:  Start of Operation, End of Operation, FSP ID, District, FOM Name, Description

3. The document upload fields (Public Notice, Attachments) should remain open so people can upload/delete documents during the commenting open status (no change to current logic)
```

**Commenting Closed Status**:
```
1. The commenting open date and commenting closed date should be locked, District should be locked.
2. The following fields should stay open: Start of operations, end of operations, FSP ID (I changed my mind from what we discussed, people should be able to change it), FOM Name, Timber Sales Manager (if applicable), Description field (should be open again), upload fields for public notice and attachments should remain open (no change to current status)
```

**Comment by ianliuwk1019** [comment]
Deployed to TEST for Julius to test.

**Comment by ianliuwk1019** [comment]
Julius tested and verified on TEST is good.
This is deployed to production today.
