### ISSUE TITLE
Urgent request - Reset FOM 1831 back to initial status.

### ISSUE THREAD

**Issue by ianliuwk1019** [bcgov/nr-fom#694]
**Describe the task**
Production request - Reset FOM 1831 back to initial status.
![image](https://github.com/user-attachments/assets/a0905adb-b717-48ae-8811-5640d4baabc6)

Also FOM 1847 (has another ticket #695).
![Image](https://github.com/user-attachments/assets/df3ed8a0-22b8-4a6e-b7a5-3e6d04a15135)

**Acceptance Criteria**
- [x] Reset 1831, 1847 (FOM production) to Initial Status.
- [ ] Let Julius verify.

**Additional context**

**Comment by ianliuwk1019** [comment]
PROD:
Before change:
![image](https://github.com/user-attachments/assets/96c39bb1-c98b-4512-a78b-ec670f182a7a)

After change:
![image](https://github.com/user-attachments/assets/edbb9471-c0a0-4c25-a1bd-bdb351f3ebbc)
![image](https://github.com/user-attachments/assets/5e5e3185-eda4-4e93-87a6-b461db42f3be)

@craigyu  @OlgaLiber2

**Comment by OlgaLiber2** [comment]
email sent to Shawna to verify and communicate the change to the licensee @ianliuwk1019 @craigyu
