### ISSUE TITLE
Cancelled FOM 1803 - update FOM description.

### ISSUE THREAD

**Issue by ianliuwk1019** [bcgov/nr-fom#699]
**Describe the task**
FOM#1803 has been withdrawn by the submitter. The submitter would like to update the FOM description as now FOM cannot be edited for the description field once it is beyond Initial state for FOM. 

**Acceptance Criteria**
- [x] Description for the FOM #1803 is updated.
- [x] Inform Julius/submitter

**Additional context**

**Comment by OlgaLiber2** [comment]
I informed Julius the description has been updated.
