### ISSUE TITLE
Renew PROD entrust certs

### ISSUE THREAD

**Issue by franTarkenton** [bcgov/nr-fom#70]
1. Follow [these instructions](https://github.com/BCDevOps/certbot/blob/master/docker/README.md) in the certbot help page to remove the existing certbot install and replace with the version maintained by common services - https://github.com/BCDevOps/certbot
1. Follow these instructions to find the billing codes, and submit a service desk ticket to get the entrust certs renewed for another year. https://apps.nrs.gov.bc.ca/int/confluence/pages/viewpage.action?pageId=95654219

**Comment by gormless87** [comment]
Certs expire mid-August; will start getting nag email soon so that Service Desk request can be submitted
