### ISSUE TITLE
Auto Database Backups

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/nr-fom#71]
Current backup is for Patroni and runs on cronjob.  We should probably use the Backup Container.

Something similar was in place for Patroni. Testing had issues, otherwise wolid.

https://github.com/bcgov/nr-fom-api/blob/8fdabe91b70da6a24be9450eb26b5a51fe88f25c/openshift/db-backup/backup-deploy.yml

Used bcgov/backup-container.

https://github.com/BCDevOps/backup-container/

**Comment by basilv** [comment]
Current backup was based on the BC gov Backup Container, despite going against Patroni :) (There was one piece that didn't work if I recall correctly, I think it was the verification of the backup didn't work with Patroni, but creating the backups worked fine.)

**Comment by ArogeG** [comment]
@DerekRoberts @basilv  how are we backing up FOM db since this ticket has not been completed?

**Comment by DerekRoberts** [comment]
@ArogeG We have to get this done prior to cutover.

**Comment by ArogeG** [comment]
Thanks @DerekRoberts, are we able to get this done before EoD tomorrow?

**Comment by DerekRoberts** [comment]
@ArogeG That's the plan!  It's just getting a little tight.
