### ISSUE TITLE
Operational Request: FOM #1655 state change from FINALIZED to COMMENT_CLOSED

### ISSUE THREAD

**Issue by ianliuwk1019** [bcgov/nr-fom#714]
**Describe the task**
Message from the business:
![Image](https://github.com/user-attachments/assets/cc7985eb-c5bc-4b0b-821b-9213d67892f7)

**Acceptance Criteria**
- [x] Update FOM 1655 to state "COMMENT_CLOSED" on production database.
- [x] Inform Sean.

**Additional context**

**Comment by ianliuwk1019** [comment]
- FOM 1655 updated:
![Image](https://github.com/user-attachments/assets/b4118450-32a3-419c-8fa9-39a1d6f9b1ed)

- Verify on prod (public):
![Image](https://github.com/user-attachments/assets/43e8f3a8-3a5a-45d9-b95a-d9b79347ee59)


Hi @OlgaLiber2 , FOM #1655 is updated to COMMENT_CLOSED

**Comment by OlgaLiber2** [comment]
@ianliuwk1019 business area is notified. You can close the ticket if there is nothing outstanding.
