### ISSUE TITLE
Cut over old/new TEST route

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/nr-fom#73]

**Comment by gormless87** [comment]
Note:  there may be users in TEST --keep Anne Marie in the loop.

**Comment by franTarkenton** [comment]
FYI - will have setup the certs for the route fom-test.nrs.gov.bc.ca
Certbot has recently been setup for the existing certs.
Link to certbot https://github.com/BCDevOps/certbot, for test we are just using letsencrypt.

**Comment by ArogeG** [comment]
Anne-Marie will be touching base with FOM business lead for this ticket. Task could take a day or two, but ideally would be more of an afternoon.

**Comment by ArogeG** [comment]
@DerekRoberts, Julius would rather we wait until after Wednesday, July 13th before changing the TEST route. Cutover should be fine between July 14th and July 21st. Please let @amee99073 know before cutover and after cutover is complete.

**Comment by DerekRoberts** [comment]
@ArogeG Will do!
