### ISSUE TITLE
Bring over old/new PROD data

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/nr-fom#75]

**Comment by ArogeG** [comment]
@DerekRoberts  @basilv  To ensure we bring over updated data there would have to be a downtime, to make sure records are not being created or edited during the data migration. This downtime needs to be communicated to the business, how much time would we require for this? The data would also need to be validated in Prod after the cutover.

**Comment by DerekRoberts** [comment]
@ArogeG We're moving data in under 5 minutes for TEST, so PROD would probably need an hour and lots of checks.  ...What error rendering markdown?

**Comment by basilv** [comment]
Remember that test has 3 years worth of data (thousands of projects), while prod just has a few records (~10 projects).

**Comment by DerekRoberts** [comment]
@basilv That's encouraging!  Most of the PROD cutover time should be for manual tests and coordinating for sign off.
