### ISSUE TITLE
Prep Pipeline for Sonarcloud Tests

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/nr-fom#76]
This likely has to do with needing more tests and consuming a .sarif or other run-file.

**Comment by basilv** [comment]
Yes, we never got around to connecting the test coverage (which we knew was low anyways). I believe with the splitting out of the API, Ian got test coverage to run (via a special package.json script), we need to use that in the github action when we run the tests (or update the package.json script that CI uses to run tests), and then ensure the coverage file gets published to SonarCloud.

**Comment by DerekRoberts** [comment]
SonarCloud is set up the same as the Greenfield and should be ready to consume lcov.info and/or cobertura-coverage.xml file when tests are included.

**Comment by basilv** [comment]
I'd say this issue is still outstanding then until we connect up the test coverage, not sure why it was closed as completed.

**Comment by DerekRoberts** [comment]
@basilv Good point.  Follow up ticket created.

https://github.com/bcgov/nr-fom/issues/101
